### ISSUE TITLE
Can not serialize generic class 

### ISSUE THREAD

**Issue by amoscatelli** [eclipse-ee4j/yasson#103]
Simple as the title states :

`
    @POST
    @Path("/find")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Override
    public FindResultDTO<ProductDTO> find() {
        FindResultDTO<ProductDTO> findResultDTO = new FindResultDTO<>();
        findResultDTO.setCount(5L);
        findResultDTO.setResults(Arrays.asList(new ProductDTO()));
        return findResultDTO;
    }

public class FindResultDTO<D extends IdentifiableDTO> {
    
    private Long count;
    private Collection<D> results;

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public Collection<D> getResults() {
        return results;
    }

    public void setResults(Collection<D> results) {
        this.results = results;
    }
    
}

`

15:23:28,737 SEVERE [org.eclipse.yasson.internal.Marshaller] (default task-1) Generating incomplete JSON
Generic bound not found for type D declared in FindResultDTO.

**Comment by amoscatelli** [comment]
If I remove generics from FindResultDTO , of course, it works

**Comment by Verdent** [comment]
Hi,
Could you please provide sample test which can reproduce this issue?

**Comment by amoscatelli** [comment]
Sorry ... I can't reproduce this anymore ...

I updated to 1.0.2 SNAPSHOT a couple of days ago.

Thx.
