### ISSUE TITLE
Avoid N different Deserializer/Serializer/Adapter for N different type

### ISSUE THREAD

**Issue by amoscatelli** [eclipse-ee4j/yasson#106]
Is it possible to declare/use a single Deserializer/Serializer/Adapter for different types ?

Let me explain :

I have many DTOs (100+) and all of them extends a common root class (IdentifiableDTO.class).

I have a Deserializer that simply manages to accomplish polymorphism by preparsing a special attribute ("@type" for completeness).

If such Deserializer implements JsonbDeserializer < IdentifiableDTO > it won't ever be called/used by JsonB for any child class, even if I annotated such class with JsonbTypeDeserializer.

So I ended up creating an Abstract generic Deserializer extended by 100+ child deserializer for each type of DTO.

I think that if I declare a JsonbTypeDeserializer on a type, or a parent type, such deserializer should be called anyway and a check on type should be made on the deserialized returned object, regarding the deserializer maybe I would only check if the type declared in the generics is assignable from the desired type.

This would be a real support for polymorphism.

What do you think ? I may help with coding if you agree with me.
I hope I explained myself.

**Comment by bravehorsie** [comment]
Sovled by #164 
Serializers/Deserializers are now allowed on subtypes.
