### ISSUE TITLE
@JsonbTypeSerializer at class level does not work

### ISSUE THREAD

**Issue by musulin** [eclipse-ee4j/yasson#109]
I am trying to serialize a class using the @JsonbTypeSerializer annotation at the class level, like:

`@JsonbTypeSerializer(AnnotatedWithSerializerTypeSerializer.class)
   public class AnnotatedWithSerializerType {
     public String value;
 }`

the test code is the following:

`public static void main(String[] args) {
final Jsonb jsonb = JsonbBuilder.create();
AnnotatedWithSerializerType annotatedType = new AnnotatedWithSerializerType();
 annotatedType.value = "def";
 System.out.println(jsonb.toJson(annotatedType));
}`

the deserializer is not called, the output is just: {"value":"def"}.
Not sure if this is a bug or the expected behaviour.

**Comment by bodote** [comment]
Its a bug, for a fix see https://github.com/eclipse-ee4j/yasson/pull/107

**Comment by m0mus** [comment]
Looks like a bug. @Verdent can you please confirm it?

**Comment by bravehorsie** [comment]
@skonx Yes, it is possible. I believe it currently doesn't work only when annotated is root type passed for serialization / deserialization.

@Verdent has a fix under way.

**Comment by skonx** [comment]
thx @bravehorsie. 
Could you please clarify?

For exemple, let's use @musulin's annotation. 
Do we have to use the `@JsonbTypeSerializer` annotation on top of `AnnotatedWithSerializerType` class or on top of a class having a field (or a method) using the `AnnotatedWithSerializerType`? 

Furthermore, correct me if I'm wrong but assuming we're talking about the first option, we will avoid to implement serializers/deserializers for the specific type (here `AnnotatedWithSerializerType`) **and** its collection usage. 
I mean we must also implement a serializer/deserializer for` List<AnnotatedWithSerializerType>` if the annotation is not yet working on top of a class... and I guess it's a harder stuff than expected.

**Comment by m0mus** [comment]
Foxed by https://github.com/eclipse-ee4j/yasson/pull/107
