### ISSUE TITLE
Adapter not working for Map key

### ISSUE THREAD

**Issue by s00r** [eclipse-ee4j/yasson#110]
I'm trying to use adapters to serialize a Map of two objects. Adapter is working fine for value but not working for the key.
Example : 
```
public class TestJsonB {

    public static void main(String[] args) {

        TestJsonB tB = new TestJsonB();
        TestAdapter test = tB.new TestAdapter();
        Map<Type, Status> mapTest = new HashMap<>();
        mapTest.put(Type.OIDVAL, Status.ACTIVE);
        test.setMap(mapTest);

        Jsonb jsonB = SerializationUtils.getJSONBuilder(false, tB.new TypeAdapter(), tB.new StatusAdapter());
        System.out.println(jsonB.toJson(test));

    }

    class TestAdapter {
        Map<Type, Status> map;

        /**
         * @return the map
         */
        public Map<Type, Status> getMap() {
            return map;
        }

        /**
         * @param map
         *            the map to set
         */
        public void setMap(Map<Type, Status> map) {
            this.map = map;
        }
    }

    enum Type {
        OIDVAL, MSISDN;
    }

    enum Status {
        ACTIVE, INACTIVE;
    }

    class TypeAdapter implements JsonbAdapter<Type, String> {

        @Override
        public String adaptToJson(Type obj) throws Exception {
            return obj.name().toLowerCase();
        }

        @Override
        public Type adaptFromJson(String obj) throws Exception {
            return Type.valueOf(obj);
        }

    }

    class StatusAdapter implements JsonbAdapter<Status, String> {

        @Override
        public String adaptToJson(Status obj) throws Exception {
            return obj.name().toLowerCase();
        }

        @Override
        public Status adaptFromJson(String obj) throws Exception {
            return Status.valueOf(obj);
        }

    }

}
```
Output is : 
```
{"map":{"OIDVAL":"active"}}
```

**Comment by Verdent** [comment]
Hi @s00r , we are not supporting adapters used on Map key at the moment. Map key is now serialized by calling method toString so if you need different output, you need to create your own toString method implemetation.

**Comment by Verdent** [comment]
Closing

**Comment by nickarls** [comment]
I would like to +1 this for re-opening. It's a bit counter-intuitive  to use the toString since the object being serialized is probably a domain object that might have needs for a descriptive toString implementation. It's also a bit surprising if someone changes the toString implementation and something seemingly unrelated breaks.

**Comment by bravehorsie** [comment]
What is the suggestion to avoid toString key calls?

**Comment by nickarls** [comment]
> What is the suggestion to avoid toString key calls?

Is this something specific for Map keys or is the behaviour the same for key values or e.g. stuff in collections? If type erasure would be a problem then nothing would work anywhere(?). If the type information is there, couldn't you just check with the proper context resolver if it can do the job?

**Comment by bravehorsie** [comment]
Lets continue the discussion in the referenced issue.
