### ISSUE TITLE
Collections of values annotated with @JsonbTypeSerializer not properly serialized

### ISSUE THREAD

**Issue by javierestevez** [eclipse-ee4j/yasson#115]
The following code (classes used below come from yasson tests):
```
AnnotatedWithSerializerType annotatedWithSerializerType = new AnnotatedWithSerializerType();
annotatedWithSerializerType.value = "original value";
Map<String, Object> map = new HashMap<>();
map.put("key", annotatedWithSerializerType);

final Jsonb jsonb = JsonbBuilder.create();
String mapJson = jsonb.toJson(map)
```
fails to produce the expected JSON below:
```
{"key":{"valueField":"replaced value"}}
```
And instead produces the JSON:
```
{"key":{"value":"original value"}}
```
ignoring the @JsonbTypeSerializer annotation on class AnnotatedWithSerializerType.

This seems to occur for collections using MapSerializer, CollectionSerializer and ObjectArraySerializer. I created tests for such cases in pull request #113.

I believe the issue comes from AbstractContainerSerializer#serializeItem which uses the model of the container instead of that of the item, loosing all customizations defined at that level. I tried to fix this on pull request #113 but I broke adapters on collections as a side effect 😉.

**Comment by Verdent** [comment]
This issue is now fixed in master.
