### ISSUE TITLE
Feature proposal - API level polymorphic support

### ISSUE THREAD

**Issue by amoscatelli** [eclipse-ee4j/yasson#133]
I think it is important to have real polymorphism support at API level.
What I DO mean is to have standardized approaches to serialize info about type and handle correct deserialization.
For example this will allow standardized ways to handle deserialization of Collection < Animal > and retrieving, for example, a specialized instance of an Horse, a Dog, a Shark (etc etc).

Yea I know there is an example about how to create a custom serializer/deserializer to handle this, but I think this kind of support should be considered as an already integrated feature declared in the spec.

Johnzon has its own implementation for this (you can find polymorphism extra library to handle this) but we need an API level feature if we really want to build portable application across different application servers.

Probably the spec should allow the user to declare the hierarchy in some way (by annotation on root or child classes or by procedural means) and should allow the user to declare a preferred strategy for type-information serialization (external property ? internal property ? key-value style (type-object)) ?

I wanted to started a discussion about this on json-b.net but I found out the GitHub is on read-only mode now. I think this could be considered for JSONB 1.1 version of the spec.

What do you think ?

**Comment by Tibor17** [comment]
+1
Implement similar `@SubTypes` annotation in Javax package like it is in Jackson.

**Comment by aguibert** [comment]
hi @amoscatelli, this is an interesting idea and certainly something that can be discussed further.  

However, the proper place to do so would be on the [JSON-B spec repo](https://github.com/eclipse-ee4j/jsonb-api), since Yasson is just one implementation of JSON-B, and you are asking for this to be added at the spec level.  

Can you please close out this issue and re-open it on the jsonb-api repo?  Then we can discuss further on that issue.

**Comment by mdzaebel** [comment]
Added https://github.com/eclipse-ee4j/jsonb-api/issues/147

**Comment by amoscatelli** [comment]
I believe this is delivered in jsonb 3.0
Thank you all
