### ISSUE TITLE
Release 1.0.2 with PrivateFieldStrategy

### ISSUE THREAD

**Issue by AdamBien** [eclipse-ee4j/yasson#137]
Current yasson implementation does not work with the PrivateFieldStrategy -> even a custom strategy breaks, because the existence of public methods makes private fields not visible.

The code already exists in your repository, but was created after this release. Please create a release 1.0.2 with FieldAccessStrategy and push it to maven central.

big thanks.

**Comment by m0mus** [comment]
We've passed the Eclipse release review and will release 1.0.2 after a new version of JSONP is released. JSONP release is currently blocked by some non-technical issues which (I hope) will be resolved soon.

**Comment by AdamBien** [comment]
Big thanks! Meanwhile I'm building JSON-B by myself -- works great, but I need it shipped with Payara... :-)

**Comment by Erik1** [comment]
Would it be possible to release 1.0.2 so servers like Wildfly can include the updated version of Yasson? 

I think it would be great for JSONB adoption, because most examples published in magazines and on websites aren't working with Yasson 1.0.1 because they put the @JsonbProperty at a private field.

**Comment by Erik1** [comment]
Is there any update when 1.0.2 will be released?

**Comment by m0mus** [comment]
We will release 1.0.2 next week.

**Comment by DennisBayer** [comment]
Hi @m0mus,
any updates for the release date of 1.0.2?

Regards

**Comment by Erik1** [comment]
> 
> 
> We will release 1.0.2 next week.

3 weeks ago you posted that it would be released next week. Is there any update on the release date?

**Comment by m0mus** [comment]
@Erik1 Sorry, there were other things to do. Some TCK tests are not passing. We are working on fixing it.

**Comment by bravehorsie** [comment]
1.0.2 is out.
