### ISSUE TITLE
Make dependencies to javax.enterprise.*, javax.naming optional

### ISSUE THREAD

**Issue by JochenHiller** [eclipse-ee4j/yasson#145]
There is an ongoing discussion in Eclipse SmartHome to replace Gson via JSON-B and Yasson as its default implementation. For more details see https://github.com/eclipse/smarthome/issues/4741

Eclipse SmartHome is intended to run on small gateways (JavaSE 8 compact 2 profile) where small footprint is important. Actually Gson needs about 235 kB. Using Yasson and JSON-P would require >620 kB overall as dependencies to CDI, javax.el and more are needed. That sounds little bit odd as these whole JSON-P and Microprofile specs should be lightweight and not linked to heavy standards.

Having a deeper look into that I assume some dependencies could be made optional. I made simple tests and saw that making packages javax.enterprise.* and javax.naming optional did work. So only JSON-P and JSON-B APIs and its implementations are sufficient. 

I changed Yasson that way:
```
Import-Package: 
  javax.enterprise.context.spi;resolution:="optional",
  javax.enterprise.inject.spi;resolution:="optional",
  ...
  javax.naming;resolution:="optional"
```

Looking into code of Yasson it looks like these dependencies would only be needed if it will introspect components at runtime using CDI.

What do you think? Would it be feasible to consider these functions as optional?

This would overall reduce the footprint to about 460 kB:

```
Bundle				Version		Bytes
javax.json-api			1.1.2	 	 31140
org.glassfish.javax.json	1.1.2		101089	
javax.json.bind-api		1.0		 23665
yasson				1.0.1		296324
```

This issue is also dependent on #144: if it would not run on compact 2 profile, it would also not make sense to strip dependencies down.

**Comment by bravehorsie** [comment]
Should be enough to make CDI API optional, together with solving #144.

**Comment by bravehorsie** [comment]
Turns out that CDI API is already optional, dependency to java.beans is removed in the PR.

**Comment by JochenHiller** [comment]
Looks good, thanks for your help
