### ISSUE TITLE
property deserialization fails

### ISSUE THREAD

**Issue by redmitry** [eclipse-ee4j/yasson#156]
Hello,

I got null deserializing a property. Here is a test:
```
public class DocumentationTest {
    private final static String JSON = "{\"general\": \"test\"}";
    @Test
    public void test() {
        try (Jsonb jsonb = JsonbBuilder.create(
                new JsonbConfig().withPropertyNamingStrategy(PropertyNamingStrategy.UPPER_CAMEL_CASE))) {
            
            final Documentation doc = jsonb.fromJson(JSON, Documentation.class);
            
            Assert.assertEquals("test", doc.getGeneralDocumentation());
        } catch (Exception ex) {
            Assert.fail(ex.getMessage());
        }
    }
    public static class Documentation {
        private String general;

        @JsonbProperty("general")
        public String getGeneralDocumentation() {
            return general;
        }

        @JsonbProperty("general")
        public void setGeneralDocumentation(String general) {
            this.general = general;
        }
    }
}
```
Changing getter/setter to getGeneral() / setGeneral() fixes it.

**Comment by redmitry** [comment]
After some investigation, I found:
**private String general;** 
field creates a property with name == "general" and read/write with jsonName == "General" (UPPER_CAMEL_CASE).

```
ClassModel.class
private boolean equalsReadName(String jsonName, PropertyModel propertyModel) {
    final String propertyReadName = propertyModel.getReadName();
    if (propertyNamingStrategy instanceof CaseInsensitiveStrategy) {
        return jsonName.equalsIgnoreCase(propertyReadName);
    }
    return jsonName.equalsIgnoreCase(propertyReadName);
}
```
Note that it **ALWAYS** compares with **equalsIgnoreCase()**!

The last return must use **equals()** instead.

Cheers,

D.

**Comment by m0mus** [comment]
Thanks for reporting! What version of Yasson you are using? I remember we fixed some equalsIgnoreCase() related bugs.

**Comment by redmitry** [comment]
1.0.2-SNAPSHOT (master branch)
https://github.com/eclipse-ee4j/yasson/blob/master/src/main/java/org/eclipse/yasson/internal/model/ClassModel.java

**Comment by redmitry** [comment]
This is a consequence of #153 and should be fixed by
https://github.com/eclipse-ee4j/yasson/pull/154

**Comment by bravehorsie** [comment]
Closing this, as referenced PR is merged and the issue closed.
