### ISSUE TITLE
AdaptedObjectSerializer and UserSerializerSerializer are not thread safe

### ISSUE THREAD

**Issue by javierpedrido** [eclipse-ee4j/yasson#157]
Hi,

The calls to jsonbContext.addProcessedObject(obj) and jsonbContext.removeProcessedObject(obj); must be sinchronized since jsonbContext is a shared object. A HashSet is being used to back the collection of processed objects (it does not support concurrent add/remove ops), you should Collections.synchronizedSet that set or use another implementation.

Regards,
Javier

**Comment by bravehorsie** [comment]
Thanks @javierpedrido this is a good catch, however synchronization on `(add/remove)ProcessedObject` won't be enough, since different runtime threads will have different contents of this collection and should not interfere with each other.

**Comment by bravehorsie** [comment]
Currently processed objects should be stored inside Marshaller/Unmarshaller instances, which are created per runtime invocation. This will fix the issue and make synchronization redundant.
