### ISSUE TITLE
Adapter check too strict?

### ISSUE THREAD

**Issue by bmhm** [eclipse-ee4j/yasson#164]
Hi everyone,

I am trying to serialize a annotation-generated implementation of my interface. For generation, I am using [immutables](http://immutables.github.io/).

For the annotation, I added: 
`@Value.Style(passAnnotations = {JsonbTypeAdapter.class, JsonbTypeSerializer.class})`
to the `package-info.java`.

Now, when I try to serialize my Objects into JSON, I get this exception:
`javax.json.bind.JsonbException: Adapter of runtime type interface my.api.Label does not match property type class my.api.ImmutableLabel`

Why should this not be possible? An ImmutableLabel implements a Label. Therefore I see no reason for the typeAdapter to fail.

Using Yasson 1.0.2. Btw: You cannot use Yasson 1.0 or 1.0.1, because it will fail to detect the annotation on the interface.
BUT: if you use Yasson 1.0 and add the type adapter manually (using the config), then it will serialize the ImmutableLabel class happily. So it DOES work, the test is just too strict.

`at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBindingFromAnnotation(AnnotationIntrospector.java:230)`

**Comment by bravehorsie** [comment]
The PR will allow `JsonbAdapters` and `JsonbSerializers` to be used for subtypes. The issue with this approach however is that supertypes may have multiple subtypes. So (in the worst case) you can declare a Serializable adapter / serializer which will be executed for all types implementing it. Same with `java.util.Collection`, `java.lang.Number`, etc.. If for example you have an adapter bound to Number type and have both Double and Integer in your pojos you will probably get ClassCastException at some point.

**Comment by bmhm** [comment]
@bravehorsie  thank you.
How was the behaviour in yasson-1.0 and yasson-1.0.1? I was able to use the JsonbAdapter using the JsonbConfig. It happily converted my implementation class to JSON. So is it a regression or is it not? I'm not too sure anymore.

I can understand why the Adapter might raise a class cast exception. In Jackson we need to define an implementation for Deserialization and hope that the interface is being used everywhere. So perhaps I should have used `@JsonbTypeSerializer` and  `@JsonbTypeDeserializer` instead.

Thanks!

**Comment by aguibert** [comment]
It looks like this issue was indeed a regression between 1.0.1 and 1.0.2.  @bravehorsie @m0mus do you think we should cut a 1.0.3 release that includes the fix (#166)?

**Comment by bmhm** [comment]
Hello @aguibert , any news about a new release? :)

**Comment by aguibert** [comment]
@bravehorsie @m0mus looks like someone created a 1.0.3 release 20 days ago:
https://github.com/eclipse-ee4j/yasson/releases/tag/1.0.3-RELEASE

However, the artifact never made its way to maven central:
https://mvnrepository.com/artifact/org.eclipse/yasson

Also, the version in pom.xml should be updated to `1.0.4-SNAPSHOT` if we really did cut a `1.0.3` release.
