### ISSUE TITLE
Bug: Deserializing java.util.Date with timezone not correct

### ISSUE THREAD

**Issue by KriechelD** [eclipse-ee4j/yasson#172]
Hello,

I've set up a simple example, thats show a problem when reading a json with a date in the format "yyyy-MM-dd'T'HH:mm:ssXXX" into an java.util.Date. The timezone is producing an incorrect result:

**Example.java:**
```
import javax.json.bind.JsonbBuilder;

public class Example {
	
	private final static String JSON_STRING = "{\"date\":\"2018-11-02T00:00:00+01:00\"}";
	
	public static void main(String[] args) {
		System.out.println(JsonbBuilder.create().fromJson(JSON_STRING, DemoDto.class).getDate());
	}
}
```

**DemoDto.java:**
```
import java.util.Date;

public class DemoDto {
	private Date date;
	public Date getDate() { return date; }
	public void setDate(Date date) { this.date = date; }
}
```

**pom.xml:**
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>de.kriechel</groupId>
	<artifactId>JsonTest2</artifactId>
	<version>1.0.0</version>
	<packaging>war</packaging>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>	
		<dependency>
			<groupId>javax.json.bind</groupId>
			<artifactId>javax.json.bind-api</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse</groupId>
			<artifactId>yasson</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.1.3</version>
		</dependency>	
	</dependencies>
</project>
```

Executing the "main" will result in the following output:
> Fri Nov 02 01:00:00 CET 2018

As you can see, the input "{"date":"2018-11-02T00:00:00+01:00"}" is dated to midnight at Timezone CET (+01:00 = CET). But the result after it was parsed by yasson is one hour later, but still in CET. So this is not correct, correct would be "Fri Nov 02 00:00:00 CET 2018".

The problem is java.util.Date. If I switch from java.util.Date to java.time.ZonedDateTime it just works fine:

**DemoDto.java**
```
import java.time.ZonedDateTime;

public class DemoDto {
	private ZonedDateTime date;
	public ZonedDateTime getDate() { return date; }
	public void setDate(ZonedDateTime date) { this.date = date; }
}
```

Output:
> 2018-11-02T00:00+01:00

So there must be some difference in the parsing between those two data types. 

I've discovered this problem, when trying to upgrade vom Java EE 7 to Java EE 8 and it seems to me that in the current state java.util.Date is not usable for all situations any more with yasson.

Any help is appreciated, this is my first issue here for yasson, so if I've missed out any information please let me know :)

Best Regards,
Dennis

## Environment ##

- **Eclipse Version**: 2018-09
- **JDK Version**: 8u192
- **org.eclipse.yasson** 1.0 / 1.0.1 / 1.0.2
- **Operating System**: Windows 10
- **Locale**: de_DE

**Comment by KriechelD** [comment]
I've took a quick look into the source code of yasson and I think I've discovered the reason. It's in the [DateTypeDeserializer.java](https://github.com/eclipse-ee4j/yasson/blob/master/src/main/java/org/eclipse/yasson/internal/serializer/DateTypeDeserializer.java#L31) class.

In Line 31:
```
private static final DateTimeFormatter DEFAULT_DATE_TIME_FORMATTER = DateTimeFormatter.ISO_DATE_TIME.withZone(UTC);
´´´
And this is used in Line 50:
```
final TemporalAccessor parsed = DEFAULT_DATE_TIME_FORMATTER.withLocale(locale).parse(jsonValue);
´´´

Here you assume that the source TimeZone in the jsonValue will always be in UTC. But the timezone can be different. If you simply remove ".withZone(UTC)" it works just fine and all Junit-Tests are still passing (tested with org.eclipse.yasson.defaultmapping.dates.DatesTest).

This is also the reason why it is working in with ZonedDateTime. Here you have the following code:
```
return ZonedDateTime.parse(jsonValue, DateTimeFormatter.ISO_ZONED_DATE_TIME.withLocale(locale));
´´´

As you can see, the ".withZone(UTC)" is not present, and thats why the code is working with ZonedDateTime but not with Date.

Best Regards,
Dennis

**Comment by KriechelD** [comment]
I've checked the history what changes have been made to the DateTypeDeserializer.java and switched back to the commit [d351dcc8c04a68e2d0c92334e045c96fefd17602](https://github.com/eclipse-ee4j/yasson/commit/d351dcc8c04a68e2d0c92334e045c96fefd17602).

If I run my code against this commit, it works perfectly well. 
So with the next commit [86d55909733011ed2d36e56492d8da3be5f0a4ac ](https://github.com/eclipse-ee4j/yasson/commit/86d55909733011ed2d36e56492d8da3be5f0a4ac) you've changed the handling of java.util.Date and leads to the wrong behavior that breaks my code.

I hope this can help you to break down the problem.

Best Regads,
Dennis

**Comment by bravehorsie** [comment]
Thanks Dennis,

`.withZone(UTC)` is meant only for parsing text where no time zone / offset is specified such as `2018-11-02T00:00:00`. In this case we use UTC, because otherwise system local zone is used. When there is an offset in parsed text, such is `2018-11-02T00:00:00+01:00` it is meant to be used instead of UTC time zone.

According to Javadoc of `#withZone(..)`:

> When parsing, there are two distinct cases to consider. If a zone has been parsed directly from the text, perhaps because DateTimeFormatterBuilder.appendZoneId() was used, then this override zone has no effect. If no zone has been parsed, then this override zone will be included in the result of the parse where it can be used to build instants and date-times.

I hope this means use value from `.withZone(UTC)` only if it not has been parsed.

I have tested your example and reproduced it on JDK 8. However starting from 9 it works as expected.
This is due to different implementation of java.time.format.Parsed#resolveInstant see [JDK changeset](http://hg.openjdk.java.net/jdk9/dev/jdk/diff/f371bdfb7875/src/java.base/share/classes/java/time/format/Parsed.java) which looks to be a bugfix.

**Comment by KriechelD** [comment]
Hello Roman,

thanks for the quick reply. You are right, according to the `.withZone(UTC)` JavaDoc the UTC should only be used when no offset was found in the parsed input. Interesseting that there has been a bugfix for JDK 9 that did no make it into the JDK 8 Updates. 

Is there any chance that yasson will be able to work in both, JDK 8 and 9, although both have different behaviors? Maybe you could implement a switch based on the JDK-Version `System.getProperty("java.version")` and then run two different parsing methods, as it is often done in Android applications.

Best Regards,
Dennis

**Comment by KriechelD** [comment]
Hi Roman,

I think I've found a possible fix that will make yasson work on both JDK 8 and 9. I've created a Pull Request (https://github.com/eclipse-ee4j/yasson/pull/173). I know the pull can not be included as is, since I'm not a contributor. I read over all the stuff that needs to be done for me to get the contributor state, but I think the bureaucracy is not worth it ;) 

Feel free to copy and use my code as you need, it's not that brilliant anyway ;)

**Comment by bravehorsie** [comment]
The relevant bug in JDK is https://bugs.openjdk.java.net/browse/JDK-8066982
According to description it should be backported to JDK8.
