### ISSUE TITLE
MapDeserializer needs to support other data types for the Key

### ISSUE THREAD

**Issue by gcameo** [eclipse-ee4j/yasson#177]
At the moment, MapDeserializer throws an error if the key for the Map is not a String. Can we add a feature to allow the JSONConfig to have a custom deserializer for the Key, like in Jackson? Or Can we extend the Deserializer framework to allow registering custom Deserializers for a Map? At the moment, Deserializers can be registered for other datatypes through Adapters but not for a Map.

**Comment by aguibert** [comment]
hi @gcameo, it's a good request for a future JSON-B spec version.  The JSON-B 1.0 spec only allows map keys for now.  Can you please instead open an issue on the JSON-B spec repo here? 
https://github.com/eclipse-ee4j/jsonb-api/issues

**Comment by gcameo** [comment]
Thanks will do
