### ISSUE TITLE
Defaulting Json objects deserialization to TreeMap instead of HashMap

### ISSUE THREAD

**Issue by srius** [eclipse-ee4j/yasson#186]
Hi everyone,

I am currently using Yasson with pojos containing generic modelisation for some attributes in oder to keep flexibility in our model : SortedMap<String,Object>. We can then mix booleans, numbers strings, arrays and objects in attribute's sublevels.

When deserializing the explicite attribute level, no problem : TreeMap is used as the attribute is delared as SortedMap. But when Json objects are met when deserializing the "value part" of the root sorted map, HashMap (DeserializerBuilder.resolveRuntimeType():221) is used as value is declared as Java Object.
Then, lexicographical order set in Jsonb config has no effect when serializing the pojo.

Why HashMap is used by default ? Is it for performance considerations ? If it not acceptable to change default behavior to TreeMap would it be possible to make it configurable ?

Regards

**Comment by aguibert** [comment]
HashMap has O(1) time complexity for get/put/remove/contains, whereas Treemap is O(log(n)), so HashMap is more efficient indeed.

If you want lexiographical ordering on "value parts", you could make your POJO datamodel be of type TreeMap instead of Map or HashMap.

**Comment by srius** [comment]
I guessed it was for performance considerations.
I don't want to explicitly define types in my data model as values can be objects (ie. maps) but also primitives or arrays.
Do we agree that if property order strategy is set in JsonbConfig, TreeMap is needed everywhere for this to work ? In order to keep performance when ordering is not needed, an alternative could be something like that in `DeserializerBuilder.java` :
```java
    private Type resolveRuntimeType() {
        Type result = ReflectionUtils.resolveType(wrapper, genericType != null ? genericType : runtimeType);
        // Try to infer best from JSON event.
        if (result == Object.class) {
            switch (jsonEvent) {
                case VALUE_FALSE:
                case VALUE_TRUE:
                    return Boolean.class;
                case VALUE_NUMBER:
                    return BigDecimal.class;
                case VALUE_STRING:
                    return String.class;
                case START_ARRAY:
                    return ArrayList.class;
                case START_OBJECT:
                    if (jsonbContext.getConfig().getProperty(JsonbConfig.PROPERTY_ORDER_STRATEGY).isPresent()) {
                        return TreeMap.class;
                    } else {
                        return HashMap.class;
                    }
                default:
                    throw new IllegalStateException("Can't infer deserialization type type: " + jsonEvent);

            }
        }
        return result;
    }
```
What do you think ?

**Comment by srius** [comment]
PR has been submitted.
