### ISSUE TITLE
Unable to deserialize a "naked" boolean

### ISSUE THREAD

**Issue by schueffi** [eclipse-ee4j/yasson#188]
According to the json specification, a "naked" boolean is a valid json document ([see rfc7159, section 13, examples, especially the last one](https://tools.ietf.org/html/rfc7159#section-13)). i.e the input
`false`
is a valid json object (note, there is no object or array around the value, and no "key": value construct.
Attempts to deserialize this into a boolean java primitive fails with NoSuchElementException:
```java
final Jsonb jsonb = JsonbBuilder.create();
boolean b = jsonb.fromJson("false", boolean.class);
```
Deserializing the other "naked" value types works fine:
```java
jsonb.fromJson("42", Long.class);
jsonb.fromJson("\"test\"", String.class);
```
The difference might be in the `BooleanTypeDeserializer`, which always "moves the parser to the next value" in deserialize, 
```java
final JsonParser.Event event = ((JsonbParser) parser).moveToValue();
```
(in contrast to the `AbstractValueTypeDeserializer`, which in turn uses the last parsed event like so:
```java
final JsonParser.Event event = ((JsonbParser) parser).getCurrentLevel().getLastEvent();
```

Unfortunately, parser.moveToValue fails for "naked" primitive values, as in such cases the value already is parsed and on top of the event stack, ready to use. Moving forward to the nextValue fails...

All of this is a problem if some wants to e.g. consume some external REST api which returns a simple true or false "boolean" as (valid) json respone.

**Comment by bravehorsie** [comment]
Propagating an issue to JSONP to allow `JsonParser` next in case of a single naked value.
