### ISSUE TITLE
Repo does not build on 'master' branch

### ISSUE THREAD

**Issue by aguibert** [eclipse-ee4j/yasson#192]
I know recently @bravehorsie made some PRs to change over to JakartaEE dependencies, but it appears that these dependencies not publicly available yet.

> [ERROR] Failed to execute goal on project yasson: Could not resolve dependencies for project org.eclipse:yasson:jar:1.0.3-SNAPSHOT: The following artifacts could not be resolved: jakarta.json.bind:jakarta.json.bind-api:jar:1.0.1, jakarta.json:jakarta.json-api:jar:1.1.5, org.glassfish:jakarta.json:jar:module:1.1.5: Could not find artifact jakarta.json.bind:jakarta.json.bind-api:jar:1.0.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

Should these changes be limited to the `EE4J_8` branch so that `master` remains usable?

Also, a general question for @m0mus and @bravehorsie... I have been making PRs against `master` branch for now, but should we be dual-delivering changes to both `master` and `EE4J_8`?

**Comment by bravehorsie** [comment]
You need to add "-P staging" to your command line in order to pull deps from https://oss.sonatype.org/content/repositories/staging/ which are not in central yet. Possibly this information can be added to project README file.

**Comment by aguibert** [comment]
@bravehorsie I've created PR #198 for enabling the staging repository in the pom.xml by default, so that people don't need to be aware of the extra `-P staging` option.  We can remove the staging repo from the pom once JakartaEE dependencies are available on Central.
