### ISSUE TITLE
getter not ignored when deserializing

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse-ee4j/yasson#199]
I am trying to deserialize JSON `{"data": ["hah"]}` into:

	public class Wrapper {
		public Wrapper() {
		}
		public ImmutableSet<String> getData() {
			return null;
		}
	}

It seems to me this should work, as “data” should be ignored during deserialization (no corresponding public field or setter). But `data` is not ignored, instead, yasson tries to create an `ImmutableSet` and fails.

Here is the relevant part of the stack trace.

	javax.json.bind.JsonbException: Can't create instance
		at org.eclipse.yasson.internal.ReflectionUtils.lambda$createNoArgConstructorInstance$1(ReflectionUtils.java:210)
	Caused by: java.lang.IllegalAccessException: Class org.eclipse.yasson.internal.ReflectionUtils can not access a member of class com.google.common.collect.ImmutableSet with modifiers ""

See this [project](https://github.com/oliviercailloux/2018-jsonb-serial) for a unit test.

**Comment by aguibert** [comment]
Hi @oliviercailloux, thanks for reporting this issue.  Looks like if we use a class that doesn't have a hidden ctor, the code ultimately behaves correctly.  In this case, Yasson tries to find the ctor for `ImmutableSet` (even though it would never be used) and blows up trying to do so.

I'll work on a fix, but in the meantime you should be able to work around the issue by putting `@JsonbIgnore` on the `getData()` method.

**Comment by oliviercailloux** [comment]
Thanks for taking care of this. No, `@JsonbIgnore` does not work around the issue, I tried that.

**Comment by oliviercailloux** [comment]
Any idea for a workaround? It’s needed while waiting for the fix to be integrated, and more importantly, because application servers around will still ship a version of yasson that doesn’t have the fix in the nearby future.

**Comment by aguibert** [comment]
Some workarounds for now:

1. Rename the `getData()` method do something that does not match the `getXXX()` property pattern, so `obtainData()` or something similar.
2. Change return type to `Set<String>` instead of `ImmutableSet<String>`

**Comment by aguibert** [comment]
3. Register an adapter for ImmutableSet like so:

```java
public static class ImmutableSetAdapter implements JsonbAdapter<ImmutableSet<String>, Set<String>> {
    @Override
    public Set<String> adaptToJson(ImmutableSet<String> obj) throws Exception {
        return obj;
    }

    @Override
    public ImmutableSet<String> adaptFromJson(Set<String> obj) throws Exception {
        return ImmutableSet.copyOf(obj);
    }
}
```

Then register the adapter with your `Jsonb` instance:
```java
Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withAdapters(new ImmutableSetAdapter()));
Wrapper obj = jsonb.fromJson("{\"data\": [\"hah\"]}", Wrapper.class);
```

**Comment by oliviercailloux** [comment]
Workaround 3 is great, thanks.
