### ISSUE TITLE
Heap pollution: Deserializing into @JsonbCreator with Set<Thing> creates a Set<HashMap> instead

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse-ee4j/yasson#201]
I am trying to deserialize `{"persons": [{"name": "name1"}]}` into a class [`Persons`](https://github.com/oliviercailloux/2018-jsonb-serial/blob/master/src/main/java/io/github/oliviercailloux/y2018/jsonb_serial/Persons.java). The class declares a JsonbCreator as follows:

	@JsonbCreator
	public static Persons wrap(@JsonbProperty("persons") Set<Person> persons)

Jsonb knows how to create a [`Person`](https://github.com/oliviercailloux/2018-jsonb-serial/blob/master/src/main/java/io/github/oliviercailloux/y2018/jsonb_serial/Person.java) from the string `{"name": "name1"}` (I have checked with another [unit test](https://github.com/oliviercailloux/2018-jsonb-serial/blob/master/src/test/java/io/github/oliviercailloux/y2018/jsonb_serial/PersonsTest.java)).

What jsonb actually puts in the variable `persons`, [however](https://en.wikipedia.org/wiki/Heap_pollution), is a `Set<HashMap>`, as determined when trying to access the first person in `persons`, which throws an exception:

	javax.json.bind.JsonbException: Exception occurred during call to JSONB creator on class: class io.github.oliviercailloux.y2018.jsonb_serial.Persons.
	Caused by: java.lang.reflect.InvocationTargetException
	Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to io.github.oliviercailloux.y2018.jsonb_serial.Person

The full code is [here](https://github.com/oliviercailloux/2018-jsonb-serial).

**Comment by oliviercailloux** [comment]
Note that removing `@JsonbCreator` and using a setter instead works.

**Comment by bravehorsie** [comment]
Thanks for reporting @oliviercailloux !

**Comment by oliviercailloux** [comment]
Whow, efficient. Thanks.

**Comment by oliviercailloux** [comment]
The problem still occurs with yasson 1.0.3 (out 28th of Dec), is this expected? (The test code is still online, see original post.)

**Comment by MytnikAA** [comment]
Same problem but with List<Thing>

**Comment by oliviercailloux** [comment]
> The problem still occurs with yasson [1.0.3](https://search.maven.org/search?q=g:org.eclipse%20AND%20a:yasson&core=gav) (out 28th of Dec), is this expected? (The test code is still online, see original post.)

Answering myself, I suppose it’s normal, as the release [notes](https://projects.eclipse.org/projects/ee4j.yasson/releases/1.0.3/bugs) do not list any issues solved.

**Comment by aguibert** [comment]
The issue is listed in the Github release notes here: https://github.com/eclipse-ee4j/yasson/releases/tag/1.0.3-RELEASE

So the attempted fix was included in 1.0.3. We'll have to take another crack at fixing the problem.

**Comment by oliviercailloux** [comment]
Switching to [1.0.4](https://search.maven.org/search?q=g:org.eclipse%20AND%20a:yasson&core=gav) (out 7th of Jan) solves the problem.

Please consider fixing the release notes…

**Comment by oliviercailloux** [comment]
Mh, the problem appears again (or a close variant of it) in another part of the code. Not sure it’s the exact same bug but the symptoms look very similar.

Please specify whether this bug fix has finally made it into 1.0.4 or not. Relatedly, whether I should just wait for a release or whether what I am observing now is a genuine new bug.

**Comment by oliviercailloux** [comment]
Oops, sorry, I was using 1.0.3 by mistake.

**Comment by Degubi** [comment]
Checked out this proplem with 1.0.5. It's working as intended. Also @oliviercailloux-s comment says that he was using 1.0.3 by accident that didn't have the fix. I think this can be closed @aguibert
