### ISSUE TITLE
Jenkins build is broken

### ISSUE THREAD

**Issue by aguibert** [eclipse-ee4j/yasson#206]
The Jenkins build at https://ci.eclipse.org/yasson/job/yasson-build/ has been failing for a few months with this error:

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
Detected JDK Version: 1.8.0-192 is not in the allowed range [9,).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.901 s
[INFO] Finished at: 2018-12-18T11:15:26-05:00
[INFO] ------------------------------------------------------------------------
```

The failure seems to be caused by this change: https://github.com/eclipse-ee4j/yasson/commit/77580b27411bdac5e37fe38285a194786224a240

I think the proper fix is to update Jenkins build to use JDK 11. However, I'm not sure if we even use this Jenkins build anymore since we now have a Travis build.  Are both Travis and Jenkins needed?

**Comment by aguibert** [comment]
@Verdent perhaps you can weigh in on this one since you seem to work with the CD/CD pipelines for this repo?

**Comment by bravehorsie** [comment]
New space for Yasson jobs is now at https://jenkins.eclipse.org/yasson/.
