### ISSUE TITLE
Unsafe initializations in version 1.0.3

### ISSUE THREAD

**Issue by realmarbro** [eclipse-ee4j/yasson#217]
As a reported and closed #216 I created a new issue to mention the 3 outstanding issues I spotted in the code.

In `org.eclipse.yasson.internal.ProcessingContext`

```java
    /**
     * Used to avoid StackOverflowError, when adapted / serialized object
     * contains contains instance of its type inside it or when object has recursive reference.
     */
    private Set<Object> currentlyProcessedObjects = new HashSet<>();
```

The above should be made final as it represents an unsafe initialization, chances are rare it results into a race condition but it is possible.

in `org.eclipse.yasson.internal.JsonbContext`

```java
    private boolean genericComponents;

    private JsonbConfigProperties configProperties;
```

`configProperties` must be made final as it represents unsafe initialization at this moment and for `genericComponents` it should be volatile or an AtomicBoolean should be used.

**Comment by bravehorsie** [comment]
@realmarbro Thanks for pointing that out, making final as many as possible is always a good practice.

Looking into code, `ProcessingContext` has a "Thread bound" mention in its javadoc. So only one thread can ever access particular instance. Anything inside is effectively thread safe. If you search for usages of the constructor of `ProcessingContext` you will see that it is created everytime `Jsonb#toJson(..), Jsonb#fromJson is called.

Situation is a bit different for JsonbContext. Its instance is cached inside `JsonBinding` class, which is shared among threads. However, please note that both of them are initialized during Jsonb instance creation and never modified after, so race condition effectively cannot occur also here. 

Neverthless, it is good idea to make all of them final to avoid any confusion. I will create a PR.
