### ISSUE TITLE
Add JMH performance tests

### ISSUE THREAD

**Issue by bravehorsie** [eclipse-ee4j/yasson#220]
Add tests to verify performance tuning for Yasson.

**Comment by nimo23** [comment]
Please also look at https://github.com/fabienrenaud/java-json-benchmark where it was verified that yasson is far behind jackson performance.

**Comment by aguibert** [comment]
@nimo23 as mentioned in the other issue, that benchmark makes no mention of Yasson. Not sure where you are getting that information from.

In any case, JMH tests were added under #238 so I"m going to close this issue

**Comment by nimo23** [comment]
@aguibert yasson is there: look at the chart on the X axis (for example, the first chart on the 3rd position from the left).
