### ISSUE TITLE
Deserialize Enum with @JsonbCreator on factory method

### ISSUE THREAD

**Issue by cchacin** [eclipse-ee4j/yasson#221]
### Given the following Enum:
```java
public enum StatusEnum {
    AVAILABLE("available"),

    PENDING("pending"),

    SOLD("sold");

    private final String name;

    StatusEnum(final String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        return String.valueOf(this.name);
    }
    
    @javax.json.bind.annotation.JsonbCreator
    public static StatusEnum fromValue(final String text) {
        return java.util.Arrays.stream(StatusEnum.values())
                .filter(b -> java.util.Objects.equals(String.valueOf(b.name), text))
                .findFirst()
                .orElse(null);
    }
}
```

### And the following wrapper class using the enum as a field type:
```java
public class EnumWrapper {
        private final StatusEnum status;

        @JsonbCreator
        public EnumWrapper(
                @JsonbProperty("status") StatusEnum status) {
            this.status = status;
        }

        public StatusEnum getStatus() {
            return status;
        }
}
```

### The following test should pass:

```java
@Test
    void testEnumDeserialization() throws Exception {
        // Given
        final Jsonb jsonb = JsonbBuilder.create();

        // When
        final EnumWrapper statusEnum = jsonb.fromJson("{\"status\":\"available\"}", EnumWrapper.class);

        // Then
        assertThat(statusEnum).isNotNull();
}
```

### Error Output:

```
java.lang.IllegalArgumentException: No enum constant models.StatusEnum.available
```

**Comment by cchacin** [comment]
@bravehorsie I added the wrapper in the example just to make my life easier in the test, but the question is:

Having an Enum which has a factory method annotated with `@JsonbCreator`, should the deserializer use the factory method or not?

**Comment by bravehorsie** [comment]
@cchacin 
First: according to [JSONB specification](https://jcp.org/aboutJava/communityprocess/final/jsr367/index.html), deserialization of enums must be done with an Enum#valueOf method. Its not perfectly clear if @JsonbCreator should apply also to enums, but lets leave enums alone and consider following scenario:
```java
public static class BoxWrapper {
        private final Box box;

        @JsonbCreator
        public BoxWrapper(
                @JsonbProperty("status") Box box) {
            this.box = box;
        }

        public Box getBox() {
            return box;
        }
    }

    public static class Box {
        private String status;

        public String getStatus() {
            return status;
        }

        @JsonbCreator
        public void Box(String status) {
            this.status = status;
        }
    }
```
During deserialization of a `BoxWrapper` we are expecting here that value for `status` is propagated through `@JsonbCreator` transitively twice - first for `BoxWrapper` creator, second for `Box` creator. That alone is the reason that Yasson currently doesn't propagate the value.  In your example `Box` is an Enum instead of a Class, but the reason for getting error is the same.

**Comment by bravehorsie** [comment]
Not sure if it meets your need but you can declare a `javax.json.bind.serializer.JsonbDeserializer` calling your factory Enum method.

**Comment by cchacin** [comment]
@bravehorsie thanks for the explanation about the spec, the `JsonbDeserializer` approach worked as a workaround for my case 👍

**Comment by cchacin** [comment]
Closing since is not an issue and there is a simple way to solve this functionality
