### ISSUE TITLE
Deserializing a java.sql.Timestamp returns a java.util.Date

### ISSUE THREAD

**Issue by TheZopo** [eclipse-ee4j/yasson#232]
Hello !
I'm using Yasson 1.0.3 on Java 11 and deserializing a java.sql.Timestamp returns a java.util.Date instead of a Timestamp. 

For instance, this test :
```java
    @Test
    public void testTimestamp() {
        Timestamp expectedTimestamp = Timestamp.from(Instant.now());

        Jsonb jsonb = new JsonBindingBuilder().build();
        String json = jsonb.toJson(expectedTimestamp);
        Timestamp timestamp = jsonb.fromJson(json, Timestamp.class);
        
        assertEquals(expectedTimestamp, timestamp);
    }
```

Will throw the following exception :
```
java.lang.ClassCastException: class java.util.Date cannot be cast to class java.sql.Timestamp (java.util.Date is in module java.base of loader 'bootstrap'; java.sql.Timestamp is in module java.sql of loader 'platform')

	at [snipped].YassonTest.testTimestamp(YassonTest.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

It's even more problematic when you have a java.sql.Timestamp argument encapsulated in an object, as the full object can't be deserialized. It throws a `java.lang.IllegalArgumentException: argument type mismatch` exeption.

**Comment by aguibert** [comment]
hi @TheZopo, thanks for reporting this. Right now Yasson does not provide a built-in adapters for `java.sql.Timestamp`.  According to JSON-B 1.0 spec, only the following date/time classes are required:
- java.util.Date
- java.util.Calendar
- java.util.GregorianCalendar
- java.util.TimeZone
- java.util.SimpleTimeZone
- java.time.*

However, Yasson also provides other adapters beyond the spec like `java.sql.Date`, so I think we could also add one for `java.sql.Timestamp` as well.

**Comment by TheZopo** [comment]
Didn't realize that `java.sql.Timestamp` wasn't in JSON-B specs, thank to pointing that out.
Howewer, as you said it could be a good improvement to add support for it, as for `java.sql.Date`.
