### ISSUE TITLE
Configuration propertsy "withNullValues" ignored when serializing Collections/Maps

### ISSUE THREAD

**Issue by reinhapa** [eclipse-ee4j/yasson#233]
When serializing collections and maps containing `null` values the `JsonbConfig` property `withNullValues` is ignored. See test provided methods:

```
import static org.junit.Assert.assertEquals;

import java.util.Collections;

import javax.json.bind.Jsonb;
import javax.json.bind.JsonbBuilder;
import javax.json.bind.JsonbConfig;

import org.junit.Test;

public class SerializationTest {
  @Test
  public void testSerializeMapWithNulls() {
    Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withNullValues(Boolean.FALSE));
    assertEquals("{}", jsonb.toJson(Collections.singletonMap(null, null)));
    assertEquals("{}", jsonb.toJson(Collections.singletonMap("key", null)));
    assertEquals("{}", jsonb.toJson(Collections.singletonMap(null, "value")));
  }

  @Test
  public void testSerializeCollectionWithNulls() {
    Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withNullValues(Boolean.FALSE));
    assertEquals("[]", jsonb.toJson(Collections.singleton(null)));
    assertEquals("[]", jsonb.toJson(Collections.singletonList(null)));
  }
}
```

**Comment by bravehorsie** [comment]
Thanks for PR @reinhapa, but I think ignoring nullValues:FALSE (which is default) for collections is intentional. 

[The specification document](https://download.oracle.com/otndocs/jcp/json_b-1-final-eval-spec/index.html) is not clear about collections, however Yasson treats them similar to Arrays, see section 3.14.2 in the spec.

The issue with ignoring null values for collections/arrays is that after serialization of collection or array of size 3, with some of the values null and deserializing it back the data will not be the same, and so process of serialization/deserialization would not be symmetric.

**Comment by reinhapa** [comment]
@bravehorsie I see your point in serializing collections though, for the Map serialization on the other hand the `null` handling does not respect the setting and also does the current implementation not behave symmetric in regards of `null` keys though. (the latter corner case is also not clearly specified, a `null` key value is silently converted to `"null"`)

**Comment by bravehorsie** [comment]
@reinhapa Key is converted to null because json doesn't allow anything else than string for key values. Correct in that cornercase Yasson is not symmetric, but it tries its best and is symmetric in other cases.

**Comment by reinhapa** [comment]
@bravehorsie should it not lead to an error if a such a case is found, so that the implementer will be aware of this fact in favour of having "wrong" data?
 
Also after a giving other thought to the Collections:
Would it be feasible to have an special implementation handling null values within `java.util.Set` then ignoring `null` values, excluding the `java.util.List`?

**Comment by bravehorsie** [comment]
@reinhapa Good suggestion, throwing exception for java.util.Map null keys is much better option than to write them as strings.

> Would it be feasible to have an special implementation handling null values within `java.util.Set` then ignoring `null` values, excluding the `java.util.List`?

Not sure what did you mean. Extending / wrapping Set implementations not allowing null values to pass in? I think Yasson could provide a setting for omitting null values on serialization for Maps/Collections/Arrays, but it should be configurable separately from null values for properties. That way the possibility of running such it is now in default mode is still possible. I also think all of the Map/List/Array should be processed in the same manner. Hopefully someone steps in at [https://github.com/eclipse-ee4j/jsonb-api/issues/118](https://github.com/eclipse-ee4j/jsonb-api/issues/118)

**Comment by reinhapa** [comment]
@bravehorsie I'm happy to help in [eclipse-ee4j/jsonb-api#118](https://github.com/eclipse-ee4j/jsonb-api/issues/118)
Also I will then remove ignore part from the Collections though..
