### ISSUE TITLE
Custom JsonbSerializer not used

### ISSUE THREAD

**Issue by cpoels** [eclipse-ee4j/yasson#240]
Hello everyone,
We are currently migrating our JavaEE applications to the latest JBoss EAP 7.2 release. Unfortunately we have some trouble with serializing (Hinbernate) entities.
I know from a previous discussion that Yasson should not provide any vendor-specific de-/serialization mechanism and I totally agree. I only want to ask a question about one specific implementation part of Yasson.

Our main problem is that the fasterxml-datatype-hibernate5 module is not working with the used Hibernate version bundled with EAP7.2 (and to be honest we want to use Jsonb). So I am currently working on JsonbSerializer for PersistentBag.

Consider following entity relation:
```
@Entity
public class User
{
    @Id
    private int id;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    private List<Address> addresses;

   // getter and setter ...
}

@Entity
public class Address
{
    @Id
    private int id;

    @OneToMany(fetch = FetchType.LAZY)
    private User user;

    // getter and setter
}

@Path("/users")
public class UserResource
{
    @PersistenceContext
    private EntityManager manager;

    @GET
    @Path("/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    public User get(@PathParam("id") final int id)
    {
        return this.entityManager.find(id, User.class);
    }
}
```

Now to the problem. My JsonbSerializer for PersistentCollection is not used when the User#addresses field is going to be serialized. I tracked it down to this implementation.

ObjectSerializer#marshallProperty()
```
//revers to ParameterizedTypeImpl List<Address>
Type genericType = ReflectionUtils.resolveType(this, propertyModel.getType());
final JsonbSerializer<?> serializer = new SerializerBuilder(marshaller.getJsonbContext())
    .withWrapper(this)
    .withObjectClass(propertyValue.getClass()) //propertyValue.getClass() is returning PersistentBag
    .withModel(propertyModel)
    .withType(genericType).build();
serializerCaptor(serializer, propertyValue, generator, ctx);
```

The final call to build() method is returning a CollectionSerializer instance. But I would expect here to get my PersistentBag serializer.
Looking into the SerializerBuilder I found the following:
```componentMatcher.getSerializerBinding(getRuntimeType(), customization) @75```
This line is not returning my serializer because `getRuntimeType()` is returning the declared type from User class and not the real runtime type PersistentBag. So my registered serializer is not recognized because `List<Address> != PersistentBag.class`

The next line @87 `getSupportedTypeSerializer(objectClass)` only returns an Optional.empty because obviously PersistentBag is not registered in DefaultSerializers.

This leads to
```
if (Collection.class.isAssignableFrom(objectClass)) {
    return new CollectionSerializer<>(this);
}
```
which is true because PersistentBag implements List.

In my opinion this is a bug, because I am registering a JsonbSerializer for a type which is unknown to Jsonb API but it's not recognized correctly.

I would appreciate your opinion on this one.

**Comment by bravehorsie** [comment]
Hi @cpoels, thanks for reporting!

Currently Yasson looks into property type signature (as is declared on field/getter) for resolving serializers / adapters without considering an instance. That looks like a bug at first glance. I will look further into it.

**Comment by cpoels** [comment]
Hello @bravehorsie, thanks for the quick response!

I haven't read the specification so far, so I'm not sure if it's really a bug or if the specification is written this way.
No matter how, it would be a pretty cool feature if an instances' type is considered, because this would open up much more configuration possibilities in my opinion.

Maybe not only checking `serializers' type == instances' type`, but also `serializers' type isAssigneableFrom instances' type`.

But as you said, I will let you have a look at it ;)

**Comment by bravehorsie** [comment]
@cpoels Looks I have been mistaken about instance type not considered. This was already fixed in #164. I've tried to create test simulating your use case (subtypes of generic collections), but my serializer is used by the runtime. Can you take if there is anything missed in the test scenario?

https://github.com/bravehorsie/yasson/tree/serializers-instance-type

https://github.com/bravehorsie/yasson/blob/71ccd671244c6984c30c31b05816dfd2c1602b13/src/test/java/org/eclipse/yasson/serializers/SerializersTest.java#L394

Or could you test your app with latest snapshots?
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/yasson/1.0.3-SNAPSHOT/

**Comment by cpoels** [comment]
@bravehorsie Thanks a lot for your help!
Unfortunately we cannot test your suggested version in our environment, becuase Yasson 1.0.3 is build with the new jakarta packages.
We are bounded to our RedHat support, so we cannot patch the Yasson module without replacing all javax.json dependencies with the jakarta.json ones. If we would do this, we would loose the support.

But your tests looks like exactly what we need. But I think we are stuck here, because we would need a Yasson build with the old "non-jakarta" packages.

**Comment by bravehorsie** [comment]
@cpoels Losing a RedHat support because updating to JakartaEE? But that is what all JavaEE went into. There will be no further updates of Yasson or other JavaEE components in the old (https://github.com/javaee/) space. Sounds like you are now stuck without any update at all, which is quite bizzare.

**Comment by cpoels** [comment]
Maybe my explanation was not that clear as I thought.
RedHat will update their Jboss EAP versions to the new JakartaEE. So for the future we won't have a problem at all.
But their latest release EAP 7.2 wont get the patches. Of course it would be somehow possible to patch Yasson 1.0.3 by ourselves, but we are then loosing the support.

Okay then, I know everything I need to know. I think we try to patch it anyway.

Thanks a lot for your support & have a nice day!

**Comment by aguibert** [comment]
It's important to note that even though the _maven dependencies_ are changing from `javax.json` to `jakarta.json`, the package names and binary .class files will all remain the same. So you should be able to run the latest Yasson 1.0.3 even if you are compiling/running against the old `javax.json` maven dependencies

**Comment by aguibert** [comment]
Closing this issue as a dup of https://github.com/eclipse-ee4j/yasson/issues/164
