### ISSUE TITLE
Order of kv-pairs wrong when using custom naming and @JsonbPropertyOrder

### ISSUE THREAD

**Issue by jesperdj** [eclipse-ee4j/yasson#258]
When you use a custom naming strategy, Yasson 1.0.3 does not handle @JsonbPropertyOrder correctly. According to the Javadoc of @JsonbPropertyOrder:

> Order in which properties are serialized. **Names must correspond to original names defined in Java class before any customization applied.**

But when I try this, it does not work: the order of the key-value pairs in JSON is different than what I specify with @JsonbPropertyOrder. To make it work, I must use the translated names instead of the original Java property names, which is against what the Javadoc documentation says.

I've found issue #23 but this does not seem to be fixed in Yasson 1.0.3.

See attached example project: [yasson-bug.zip](https://github.com/eclipse-ee4j/yasson/files/3051727/yasson-bug.zip)

**Comment by jesperdj** [comment]
Note: In the example I'm using my own implementation of interface PropertyNamingStrategy, not one of the pre-defined ones as in issue 23.

**Comment by aguibert** [comment]
thanks for reporting this one @jesperdj. @Verdent has proposed a fix which is now merged so this should be included in the next version of Yasson
