### ISSUE TITLE
Convert JsonObject to class object efficiently

### ISSUE THREAD

**Issue by mdzaebel** [eclipse-ee4j/yasson#259]
A JsonObject can be transformed into it's corresponding class instance via:
`Dog dog=JsonbBuilder.create().fromJson(jsonObject.toString(), Dog.class)`

However, it seems to be inefficient to use _jsonObject_.**toString**() as a String is an other intermediate representation, that contains the same information. I need to transform the _jsonObject_ before the object binding. So is there a more efficient way to achieve the binding from a JsonObject?

**Comment by aguibert** [comment]
Marc asked the same question on StackOverflow, where I've provided the current answer which is basically "no": https://stackoverflow.com/questions/55677292/convert-jsonobject-to-pojo-efficiently-with-json-b-1-0-e-g-yasson-java-ee-8

I think the best thing we can do to handle this use case is address it at the spec-level in https://github.com/eclipse-ee4j/jsonb-api/issues/111

**Comment by bravehorsie** [comment]
Good point. The problem with including JSONP objects, is that Jsonb interfaces and Yasson internal classes are built on top of `JsonGenerator/JsonParser` (for example [JsonbSerializer](https://github.com/eclipse-ee4j/jsonb-api/blob/master/api/src/main/java/javax/json/bind/serializer/JsonbSerializer.java)). What comes to my mind is to implement JsonParser / JsonGenerator in Yasson, which input / output will be JsonStructure. Not sure if this is the best approach in terms of performance and design, but would definitely work.

**Comment by mdzaebel** [comment]
Sounds quite reasonable.
