### ISSUE TITLE
Turn JsonbComponentInstanceCreator into a service provider interface

### ISSUE THREAD

**Issue by mkouba** [eclipse-ee4j/yasson#260]
So that an integrator could provide a custom implementation of this interface. `JsonbComponentInstanceCreatorFactory` currently contains some reflection magic to detect the presence of a CDI container. In fact, the presence of the CDI API is enough.

I believe it would be reasonable to define this SPI. [Quarkus](https://github.com/quarkusio/quarkus) integration would definitely make use of it because our DI solution is compatible with CDI but we don't support all "portable extensions related" SPIs (they do not fit into our build time metadata processing approach) and so the invocation of  the `BeanManagerInstanceCreator#getOrCreateComponent()` fails.

**Comment by gsmet** [comment]
Any thought on this? This is rather blocking for the Yasson Quarkus integration and we have quite a few users asking for it.

**Comment by aguibert** [comment]
Can you elaborate on what needs to happen in order to turn this into an SPI? Are you asking that we make a `META-INF/service/` entry for this?  Or perhaps just moving it out of the Yasson `.internal` package so it is exported by our JPMS module?

**Comment by mkouba** [comment]
Just use the `ServiceLoader` to obtain the `JsonbComponentInstanceCreator` instance so that an integrator could provide its own implementation. The logic from `JsonbComponentInstanceCreatorFactory` should be extracted to a default impl (e.g. `DefaultJsonbComponentInstanceCreator`) and either moved to a separate artifact with `META-INF/service` config, or alternatively `JsonbComponentInstanceCreator` could define a priority (e.g. `default int getPriority() { return 1; }`) and the instance with the highest priority is used.

**Comment by aguibert** [comment]
Sounds like a reasonable change -- do you have cycles to propose a PR?

**Comment by mkouba** [comment]
Yes, I'll try to prepare something.

**Comment by geoand** [comment]
I can work on this next week when I am back if you haven't had time to do
it until the @mkouba

**Comment by gsmet** [comment]
@bravehorsie @aguibert is the next release already scheduled? Asking that so that we don't miss it and do the appropriate work in Quarkus as soon as it is released.

Thanks!

**Comment by bravehorsie** [comment]
@gsmet @aguibert Lets review current PRs and do the release.

**Comment by masini** [comment]
Thank you for fixing this issue, is a blocking one for our porting to JSONB.

**Comment by gsmet** [comment]
@bravehorsie @aguibert any news on the release front?

Thanks!

**Comment by aguibert** [comment]
@bravehorsie I added a code review to #262 (your big JSON-P interop PR) and I think we should merge it and then we should be good to cut a new release.

**Comment by bravehorsie** [comment]
Yasson 1.0.4 has been released to central, which includes the fix.

**Comment by gsmet** [comment]
Thanks @bravehorsie !
