### ISSUE TITLE
generic bound not found for type M declared in class

### ISSUE THREAD

**Issue by gjsbe** [eclipse-ee4j/yasson#273]
Hi,
for many time I correctly developed a java ee ear that runs on wildfly 13, that use yasson-1.0.1.
Inside I use jackson for serializing my java beans to JSON.
These java beans uses generics type, on wildfly 13 everything works perfectly.

```
public class JsonModelResult\<M\> extends JsonResult {
	private String jsonKey;
	private M model;

	public String getJsonKey() {
		return jsonKey;
	}

	public void setJsonKey(String jsonKey) {
		this.jsonKey = jsonKey;
	}		
	
	public M getModel() {
		return model;
	}

	public void setModel(M model) {
		this.model = model;
	}
}
```

Now I am making tests to migrate to wildfly 17, it use yasson-1.0.3.
The same code doesn't work more, on the log i see these message:

WARNING [org.eclipse.yasson.internal.ReflectionUtils] (default task-1) Generic bound not found for type M declared in class JsonModelResult.

If I substitute yasson-1.0.3 with yasson-1.0.1 to wildfly 17 everything works.
I'm going crazy, I didn't understand what changed from 1.0.1 to 1.0.3.
Thank you very much.

**Comment by aguibert** [comment]
hi @gjsbe, in order for this issue to be investigated, can you please update with more detailed information such as:
 - the `JsonResult` class that `JsonModelResult<M>` is extending
 - The full stack trace of the error you are seeing
 - Is this error happening on serialization (Java Object -> JSON) or on deserialization (JSON -> Java Object)?

Also, if you are able to extract out the code to reproduce this issue in a standalone test case that would be the best option.

**Comment by gjsbe** [comment]
Hi, 
wildfly doesn't show any error, In log I see only the warning:
"generic bound not found for type M declared in class JsonModelResult"
Here's JsonResult class:

```
@Dependent
@JsonRes(content = JsonContent.Result)
public class JsonResult {		
    private Boolean result;
	private List<JsonFieldError> fieldErrors;
    private List<JsonErrorMessage> errorMessages;
	private List<String> infoMessages;	

    public Boolean getResult() {
        return result;
    }

    public void setResult(Boolean result) {
        this.result = result;
    }

	public List<JsonErrorMessage> getErrorMessages() {
		return errorMessages;
	}

	public void setErrorMessages(List<JsonErrorMessage> errorMessages) {
		this.errorMessages = errorMessages;
	}

	public List<JsonFieldError> getFieldErrors() {
		return fieldErrors;
	}

	public void setFieldErrors(List<JsonFieldError> fieldErrors) {
		this.fieldErrors = fieldErrors;
	}

	public List<String> getInfoMessages() {
		return infoMessages;
	}
	
    public void setInfoMessages(List<String> infoMessages) {
		this.infoMessages = infoMessages;
	}    
    
	public void addFieldError(JsonFieldError fieldError) {
		
		if(fieldErrors == null) {
			fieldErrors = new ArrayList<>(1);			
		}
		
		fieldErrors.add(fieldError);
	}
	
	public void addErrorMessage(JsonErrorMessage errorMessage) {
		
		if(errorMessages == null) {
			errorMessages = new ArrayList<>(1);			
		}
		
		errorMessages.add(errorMessage);
	}
	
	public void addInfoMessage(String infoMessage) {
		
		if(infoMessages == null) {
			infoMessages = new ArrayList<>(1);			
		}
		
		infoMessages.add(infoMessage);
	}
}

```
And this is JsonModelResult:

```
@Dependent
@JsonRes(content = JsonContent.Model)
public class JsonModelResult<M> extends JsonResult {
	private String jsonKey;
	private M model;

	public String getJsonKey() {
		return jsonKey;
	}

	public void setJsonKey(String jsonKey) {
		this.jsonKey = jsonKey;
	}		
	
	public M getModel() {
		return model;
	}

	public void setModel(M model) {
		this.model = model;
	}
}

```
I paste also a portion of the code of the method that gives that warning:

```
@Path("/path")
@RequestScoped
public class MyWs {
       
        @Inject
        MyEjb ejb;

        @GET
        @Path("/{id: [0-9]*}")
        @Produces(MediaType.APPLICATION_JSON)
        public JsonModelResult<Bean> getDet(int id) throws Exception {
              JsonModelResult<Bean> bean = ejb.getDet(id);
              return bean;
        }
}

```

And finally

```
@Provider
public class JsonProvider implements ContextResolver<ObjectMapper> {
      private final ObjectMapper mapper = new ObjectMapper();

      public ObjectMapper getContext(Class<?> type) {
                mapper.registerModule(new JsonModule());
                return mapper;
       }

       private class JsonModule extends SimpleModule {

                public JsonModule() {
                        super();
                        this.addSerializer(JsonModelResult.class, new JsonModelSerializer());
                }
        }

         private class JsonModelSerializer extends JsonSerializer<JsonModelResult> {

               public void serialize(
                        JsonModelResult model, JsonGenerator generator, SerializerProvider provider
                ) throws IOException, JsonProcessingException {
                        // this method is no more reached and wildfly process everything to json without passing from here.
                }
         }
}

```

I made many tests today on wildfly 17, for many hours I searched for the bug inside jackson (a mine bug), but when I changed yasson to previous previous version, and everything restarted working correctly, I opened here the issue.
But I am not sure the code is scalable and complicated, so I'm not sure that can be a yasson problem, maybe it's a mine problem anyway.
Thank you very much
Regards

**Comment by gjsbe** [comment]
I have another possible scenario, if the new version of yasson is more strict, I made some error inside CDI and with the new version the error comes out.

**Comment by gjsbe** [comment]
Hi,
today I'm trying again to find a workaround or a solution to the problem.
The problem is inside ReflectionUtils.java:

```
if (item == null) {
            //Bound not found, treat it as an Object.class
            logger.warning(Messages.getMessage(MessageKeys.GENERIC_BOUND_NOT_FOUND, typeVariable, typeVariable.getGenericDeclaration()));
            return Object.class;
 }
```
The strange thing is that it returns Object.class and should go on, but the method (jackson related) serialize inside JsonModelSerializer is never called and yasson serialize the entire object without my customization.
Based on the fact that If I load inside wildfly 17 the previous version of yasson (1.0.1), it's like Jackson calls some method inside yasson library and is no more able to call custom serializer because it doesn't find a valid mapping.
I tried also using 

this.addSerializer(JsonResult.class, new JsonResultSerializer());

and 

```
private class JsonResultSerializer extends JsonSerializer<JsonResult> {

public void serialize(
	JsonResult model, JsonGenerator generator, SerializerProvider provider
) throws IOException, JsonProcessingException {
        ///code
}
```
but anything change, I don't see any difference.
Thank you very much
Regards

**Comment by gjsbe** [comment]
Is not a bug, today I understood the problem. 
Sorry.

**Comment by flinthart** [comment]
Hi gjsbe - can you let me know what you found?  I'm having a similar issue...
Thank you

**Comment by gjsbe** [comment]
Hi,
the answer is not yasson related, I use yasson in wildfly environment as module.
The problem was after migrate an ear from wildfly 13 to wildfly 17.
The answer is that wildfly 13 use jackson, wildfly 17 comes with java ee 8 and use json-b embedded module.
This was my error, it was a mine error, not yasson related.
Bye

**Comment by aguibert** [comment]
hi @flinthart, feel free to open a separate issue and we can look at it there
