### ISSUE TITLE
How to exclude Weld metadata from JSON object serialization by Yasson

### ISSUE THREAD

**Issue by akovac35** [eclipse-ee4j/yasson#281]
Details posted here:

https://stackoverflow.com/questions/56951279/how-to-exclude-weld-metadata-from-json-object-serialization-by-yasson

Here is approximate call stack:
	at org.eclipse.yasson.internal.model.GetValueCommand.getValue(GetValueCommand.java:36)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.getValue(ReflectionPropagation.java:73)
	at org.eclipse.yasson.internal.model.PropertyModel.getValue(PropertyModel.java:285)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:80)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:61)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:148)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:76)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:102)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:153)
	at com.ibm.ws.jaxrs21.providers.json.JsonBProvider.writeTo(JsonBProvider.java:171)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1474)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils$3.run(JAXRSUtils.java:1471)
	at java.security.AccessController.doPrivileged(AccessController.java:703)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1471)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:249)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:124)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:85)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:90)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:124)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:275)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:134)

**Comment by aguibert** [comment]
It looks like [Weld CDI beans](https://github.com/weld/api/blob/master/weld/src/main/java/org/jboss/weld/proxy/WeldClientProxy.java#L34) have a few public methods inserted onto them that match the default criteria for a JSON-B property:
```java
public interface WeldClientProxy extends WeldConstruct {

    Metadata getMetadata();

    public interface Metadata {
        Bean<?> getBean();

        Object getContextualInstance();
    }
}
```

Which explains why you are getting the extra `metatdata` property on your JSON
```json
{
  "accessCounter": 1,
  "firstName": "test",
  "lastName": "test",
  "metadata": {
    "contextualInstance": {
      "accessCounter": 2,
      "firstName": "test",
      "lastName": "test"
    },
    "instance": {
      "accessCounter": 3,
      "firstName": "test",
      "lastName": "test"
    }
  }
}
```

The easiest solution would be to have WELD put `@JsonbIgnore` on their `getMetadata()` method, but this would probably introduce a dependency on the JSON-B API for them.

@manovotn what do you think?

The other option I can think of is to add a special case in Yasson to see if the model object is an instanceof `WeldClientProxy` and if it is we would exclude the `metadata` property.

**Comment by manovotn** [comment]
Hmm, I am not all that familiar with Yasson, why does it even try to serialize a proxy?
Is it the method signature that matches something Yasson inspects via reflection?

> The easiest solution would be to have WELD put @JsonbIgnore on their getMetadata() method, but this would probably introduce a dependency on the JSON-B API for them.

We're definitely not adding that. Weld is used in environments where there doesn't need to be JSON-B API present.

> The other option I can think of is to add a special case in Yasson to see if the model object is an instanceof WeldClientProxy and if it is we would exclude the metadata property.

Yeah, that sounds plausible. If Yasson people are OK with that of course.

**Comment by akovac35** [comment]
I would caution against Weld dependency in Yasson code, and reflection will cause slowdowns. Perhaps a clear design pattern would be a better solution. I have suggested one in stackoverflow, perhaps it I should document it in this projects *.md document?

**Comment by akovac35** [comment]
Ok, so I checked update #302 and it seems it will not introduce additional overhead, so it seems as a good solution.

**Comment by aguibert** [comment]
@manovotn In case you are not familiar, Yasson is the Ref Impl for JSON-B. If an application wants to convert any POJO -> JSON can do that by inspecting the class with reflection by looking for getter and setter methods (or public fields).

If I create a simple CDI bean like this:
```java
@RequestScoped
public class PersonBean {

    private String name;
    private int age;

    // < standard public getters and setters >
}
```

And then inspect the methods of this bean, here is the output:
```
class is: class jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy
  Method Name                   Method.toString()
  ============                  ==============
  setName                       public void jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.setName(java.lang.String)
  weld_getTargetInstance        public java.lang.Object jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.weld_getTargetInstance()
  getAge                        public int jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.getAge()
  getMetadata                   public org.jboss.weld.proxy.WeldClientProxy$Metadata jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.getMetadata()
  getName                       public java.lang.String jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.getName()
  weld_getHandler               public org.jboss.weld.bean.proxy.MethodHandler jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.weld_getHandler()
  weld_getTargetClass           public java.lang.Class jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.weld_getTargetClass()
  lifecycle_mixin_$$_postConstruct   public void jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.lifecycle_mixin_$$_postConstruct()
  weld_setHandler               public void jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.weld_setHandler(org.jboss.weld.bean.proxy.MethodHandler)
  lifecycle_mixin_$$_preDestroy public void jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.lifecycle_mixin_$$_preDestroy()
  setAge                        public void jsonb.cdi.web.PersonBean$Proxy$_$$_WeldClientProxy.setAge(int)
  <methods inherited from java.lang.Object not shown>
```

So it looks like most of the methods automatically added by weld are prefixed with `weld_` which is nice, but `getMetadata` is not, and therefore it matches the default public getter/setter detection and is being included in the JSON output.

So Matej, what do you think would be the most reliable way to tell from reflection if we are looking at the `getMetadata` object, without adding a compile dependency on WELD. My current approach is in PR #302 which I see you reviewed (thanks!), but I'm wondering if we should also check to see if the class name String ends with `$Proxy$_$$_WeldClientProxy` -- do you think this will be a long-term reliable check?

**Comment by manovotn** [comment]
> So it looks like most of the methods automatically added by weld are prefixed with weld_ which is nice, but getMetadata is not,

Yeah, that's intentional. Those prefixed are internal-only, whereas the `getMetadata` is part of Weld API to unwrap a proxy (although rarely used, it can be handy).

> but I'm wondering if we should also check to see if the class name String ends with $Proxy$_$$_WeldClientProxy -- do you think this will be a long-term reliable check?

Don't do that. While the suffix hasn't changed in eons, you would be relying on internal bits. Also note that it is slightly different for beans that use decorators/interceptors - a subclass is generated and then a proxy on top of that which changes the name of the final class. But it would still end in `$$_WeldClientProxy`.
Your current PR does it perfectly IMO, the [check for return type](https://github.com/eclipse-ee4j/yasson/pull/302/files#diff-0b679cdd432a9709d06c281d3ac6656bR200) is robust enough. Can you imagine a situation where you find a method with the same signature *and* a return type `org.jboss.weld.proxy.WeldClientProxy$Metadata` which you wouldn't want to skip?

**Comment by bravehorsie** [comment]
I would suggest to raise an improvement on jsonb-api to add configuration support to skip any properties by their string name on a particular class. Similar is currently possible with implementing custom `javax.json.bind.config.PropertyVisibilityStrategy`, but it does operate globally and is a bit cumbersome to use.

**Comment by manovotn** [comment]
That's interesting idea but it would get a bit verbose basing it on a class - in this case all proxied beans will have the `getMetadata`.
You could maybe achieve the same by adding a property that would ignore certain method based on name and return type. Then again, user would need to care, whereas current solution works with no additional effort (but hardwires it, that's true).

**Comment by bravehorsie** [comment]
Most annotations from Jsonb class level could be put also at package level which will save some copypasting in your case. Weld is not the only framework creating proxies, similar does Hibernate for example. Do we want to exclude all of them hardcoding property parsing adaptations?

**Comment by manovotn** [comment]
Then we could have an annotation that users can put into their class that will say what methods are to be ignored (since `@JsonbTransient` cannot be used on classes). This will obviously require user to know what he/she wants to exclude but at least gives them some control if they really need to have proxied objects exposed as POJOs via JSON.

**Comment by aguibert** [comment]
> Weld is not the only framework creating proxies, similar does Hibernate for example. Do we want to exclude all of them hardcoding property parsing adaptations?

As long as the number of special cases remains relatively low I think this is OK. For example, we just need 1 hardcoded check for OOTB integration with CDI beans, 1 check for integration with Groovy, and if we have to add 1-2 checks for OOTB integration with JPA I think that is also worth it.

The general solution to applying JSON-B customizations to existing classes at runtime is being discussed here:
https://github.com/eclipse-ee4j/jsonb-api/issues/88
And I think once JSON-B supports this mechanism, we can change Yasson from using these hardcoded checks to using the spec-way of doing it (but still have it pre-configured for the user)

**Comment by akovac35** [comment]
It would certainly make sense to have the ability to define ignore lists for certain package, class and method name patterns in advance. Be aware that Yasson is used in enterprise enviroments where code is autogenerated and where there is havy use of proxies and aspectj. Having to manually define ignore lists by setting annotations to classes or methods is virtually impossible in practice - modifying a class once it was generated is ok, but what about when code is regenerated, annotations will be lost then.
