### ISSUE TITLE
How to get rid of extra quotes around string values when serializing JsonArray

### ISSUE THREAD

**Issue by Degubi** [eclipse-ee4j/yasson#282]
Hi! I got a question, not an issue.
How can I get rid of the extra quotes that I get when I serialize an array of strings to string format.? Example:

```
var strList = List.of(channelQueryHistory.data);   //List<String>
var test = Json.createArrayBuilder(strList).build();  //JsonArray
var arrayStr = Main.json.toJson(test);   //String, Main.json is a Jsonb instance with formatting set to true
```

What I'd expect:
["Fortnite",
 "Half-Life",
 "Generation Zero",
 "Layers of Fear 2"
  ]

What I get:
["\\"Fortnite\\"",
 "\\"Half-Life\\"",
 "\\"Generation Zero\\"",
 "\\"Layers of Fear 2\\""
]

**Comment by aguibert** [comment]
What is the input being used as `channelQueryHistory.data`?

If I try this locally, I get expected results:
```java
        List<String> strList = new ArrayList<>();
        strList.add("first");
        strList.add("second");
        JsonArray test = Json.createArrayBuilder(strList).build(); // JsonArray
        String arrayStr = jsonb.toJson(test);
        System.out.println(arrayStr);
```
prints:
`["first","second"]`

**Comment by aguibert** [comment]
My guess is that your input data has an extra set of escaped quotes like this:
```java
        List<String> strList = new ArrayList<>();
        strList.add("\"first\"");
        strList.add("\"second\"");
```

**Comment by Degubi** [comment]
Nice catch! It's because the JsonValue::toString method adds them when I read back my settings.json file. (I'm working on switching from gson)

```
public HistoryQueue(JsonArray data, int historySize) {
	this.data = data.stream().map(JsonValue::toString).limit(historySize).toArray(String[]::new); //It happens after mapping
	this.maxLen = historySize;
}
```
Is there an alternative method to convert a JsonValue to a string without it adding the extra quotes?

**Comment by aguibert** [comment]
If you are reading JSON from a file, my recommendation would be to skip over the intermediate conversion to JSON-P objects (e.g. `JsonArray`) and just go straight to a POJO using JSON-B.

Have a look at `Jsonb.fromJson(InputStream, Class<?>)`. If you need to customize the reading further (I see you are doing `limit(historySize)` that's fine. 

If you need to stick with the JSON-P APIs, then it's important that you understand the distinction between `JsonValue::toString` and `JsonString::getString`. The former gives you the raw text representing the JSON data, and the latter gives you the normalized JSON value -- which is what you are expecting in this case.

To illustrate:
```java
        JsonString val = Json.createValue("foo");
        System.out.println(val.toString());  // prints "foo"
        System.out.println(val.getString());  // prints foo
```

**Comment by Degubi** [comment]
Thank you for the explanation! I solved it with using a JsonString.
