### ISSUE TITLE
json string prints new line between property and value

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#289]
When printing any json string to the logger (e.g. slf4j, log4j), then the output in the console is:

```
// json string prints new line between property and value
{
 "id": 
  1,
  "name":
  "ted",
  "description": null
}
```

instead of 

```
{
  "id": 1,
  "name": "ted",
  "description": null
}
```

_tested with org.eclipse.yasson 1.0.4_

**Comment by aguibert** [comment]
hi @nimo23, can you provide more details on your configuration?

- What is your log4j.properties or logging config?
- What is your JSON-B config? It looks like you have `withFormatting(true)` set?
- What is the raw string value of the JSON you are attempting to output?

I attempted to reproduce this locally and everything behaved as expected for me.

log4j.properties:
```
# Set root logger level to DEBUG and its only appender to A1.
log4j.rootLogger=DEBUG, A1
# A1 is set to be a ConsoleAppender.
log4j.appender.A1=org.apache.log4j.ConsoleAppender
# A1 uses PatternLayout.
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n
```

main java class:
```java
public class AGGMain {

    public static class User {
        public long id;
        public Set<String> roles;
        public String name;
        public int age;
    }

    // tested with and without formatting
    private static final Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(true));

    public static void main(String args[]) throws Exception {
        User u = new User();
        u.id = 84795629346L;
        u.name = "Andy";
        u.age = 26;
        Logger log = LoggerFactory.getLogger(AGGMain.class);
        log.info(jsonb.toJson(u));
    }

}
```

The resulting output was as expected:
```
0    [main] INFO  atest.AGGMain  - 
{
    "age": 26,
    "id": 84795629346,
    "name": "Andy"
}
```
with formatting on. With formatting=off it was all on one line as expected

**Comment by nimo23** [comment]
1. the jsonb-config:

```
var jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(true).withNullValues(true)
.withPropertyVisibilityStrategy(new PrivateVisibilityStrategy());
```


2. the logger config (used within wildfly version 17):

```
<formatter name="COLOR-PATTERN">
    <pattern-formatter pattern="%K{level}%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"/>
</formatter>
```

**Comment by aguibert** [comment]
does the same issue occur when you run the code outside of Wildfly? I'm thinking this has to be some sort of interaction caused by using Yasson with Wildfly's loggers.

**Comment by nimo23** [comment]
>does the same issue occur when you run the code outside of Wildfly

No. Outside of wildfly the json string prints normally without line breaks.

Strange. I dont know why? Could you give me a solution to work within wildfly? Why does this happen? 

Should I adapt this pattern somehow? 

`<pattern-formatter pattern="%K{level}%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"/>`

**Comment by aguibert** [comment]
I am not familiar with Wildfly logging, so perhaps it would be better to discuss with that community.

A good experiment would be to do:
`System.out.println("first \n second")` 
in wildfly and see if there is an extra line break added or not.

In any case, the "pretty printing" details are not controlled by Yasson or JSON-B -- we simply set `javax.json.stream.JsonGenerator.PRETTY_PRINTING=true` on the underlying JSON-P generator and it inserts the linebreaks and whatnot.

**Comment by nimo23** [comment]
>in wildfly and see if there is an extra line break added or not.

Yes, Wildfly prints the line break with `System.out.println("first \n second")`. Wildfly uses `javax.json-1.1.2.jar`. However, you can close this issue as this is not caused by Yasson.

**Comment by nimo23** [comment]
I have used json-p directly within wildfly and it prints as it should - without line breaks between property and value. So I am wondering why this works but with yasson not?

v```
ar json = Json.createObjectBuilder()
				.add("name", "Name 1")
				.add("task", "Task 1")
				.add("isNull", "null")
				.add("born", 1)
				.build();
		var config = Map.of(JsonGenerator.PRETTY_PRINTING, true);
		var jwf = Json.createWriterFactory(config);
		var sw = new StringWriter();
		try (var jsonWriter = jwf.createWriter(sw)) {
			jsonWriter.writeObject(json);
			System.out.println(sw.toString());
		}
```

**Comment by aguibert** [comment]
Perhaps you could try doing a runtime comparison of both strings?
For example:
```java
var jsonpString = // get string from JSON-P directly
var jsonbString = // get string from JSON-B
```
you could see if they `.equal()` each other, or if their lengths are the same, and if not you could step through the strings char by char and see if any hidden chars (maybe `\n\r`) are getting added in anywhere

**Comment by nimo23** [comment]
I use this class to test json-b and json-p output:


```
import java.io.Serializable;
import java.io.StringWriter;
import java.text.Collator;
import java.util.Map;

import javax.json.Json;
import javax.json.bind.Jsonb;
import javax.json.bind.JsonbBuilder;
import javax.json.bind.JsonbConfig;
import javax.json.bind.annotation.JsonbNillable;
import javax.json.bind.annotation.JsonbPropertyOrder;
import javax.json.stream.JsonGenerator;

@JsonbNillable(value = true)
@JsonbPropertyOrder(value = { "name", "task", "born" })
public class Tada implements Serializable {

	private static final long serialVersionUID = 2913625996208980629L;

	public static Tada createDefaultInstance() {
		Tada t = new Tada();
		t.setName("myname");
		t.setTask("mytask");
		return t;
	}

	/**
	 * @param tada
	 * @return json string by Json-P
	 */
	public static String toJsonByJsonP(Tada tada) {
		var json = Json.createObjectBuilder()
				.add("name", tada.name)
				.add("task", tada.task)
				.build();
		var config = Map.of(JsonGenerator.PRETTY_PRINTING, true);
		var jwf = Json.createWriterFactory(config);
		var sw = new StringWriter();
		try (var jsonWriter = jwf.createWriter(sw)) {
			jsonWriter.writeObject(json);
			return sw.toString();
		}
	}

	/**
	 * 
	 * @param tada
	 * @return json string by Json-B
	 */
	public static String toJsonByJsonB(Tada tada) {
		try (Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(true))) {
			return jsonb.toJson(tada);
		} catch (Exception e) {
			return null;
		}
	}
	
	public static boolean jsonStringIsEquals(String jsonP, String jsonB) {
		
		System.out.println("Json by Json-B:");
		System.out.println(jsonB);
		
		System.out.println("Json by Json-P:");
		System.out.println(jsonP);
		
		int compare = Collator.getInstance().compare(jsonP, jsonB);
		System.out.println("json strings are equal: "  + jsonP.equals(jsonB));
		System.out.println("json contents are equal: "  + jsonP.contentEquals(jsonB));
		System.out.println("json contents are equal: "  + compare);
		
		System.out.println("jsonP contains \\n\\r: "  + jsonP.contains("\\n\\r"));
		System.out.println("jsonB contains \\n\\r: "  + jsonB.contains("\\n\\r"));

		return jsonP.equals(jsonB);
	}

	private String name;
	private String task;
	
	public String getName() { return name;}
	public void setName(String name) { this.name = name;}
	
	public String getTask() { return task;}
	public void setTask(String task) { this.task = task;}
}
```

and the output is the following within wildfly:

```
18:03:21,927 INFO  [stdout] 
18:03:21,927 INFO  [stdout] {
18:03:21,927 INFO  [stdout]     "name": "myname",
18:03:21,927 INFO  [stdout]     "task": "mytask"
18:03:21,927 INFO  [stdout] }
18:03:21,928 INFO  [stdout] 
18:03:21,928 INFO  [stdout] {
18:03:21,928 INFO  [stdout]     "name": 
18:03:21,928 INFO  [stdout]     "myname",
18:03:21,928 INFO  [stdout]     "task": 
18:03:21,928 INFO  [stdout]     "mytask"
18:03:21,928 INFO  [stdout] }
18:03:21,928 INFO  [stdout] Json by Json-B:
18:03:21,929 INFO  [stdout] 
18:03:21,929 INFO  [stdout] {
18:03:21,929 INFO  [stdout]     "name": 
18:03:21,929 INFO  [stdout]     "myname",
18:03:21,929 INFO  [stdout]     "task": 
18:03:21,929 INFO  [stdout]     "mytask"
18:03:21,929 INFO  [stdout] }
18:03:21,929 INFO  [stdout] Json by Json-P:
18:03:21,929 INFO  [stdout] 
18:03:21,929 INFO  [stdout] {
18:03:21,929 INFO  [stdout]     "name": "myname",
18:03:21,930 INFO  [stdout]     "task": "mytask"
18:03:21,930 INFO  [stdout] }
18:03:21,952 INFO  [stdout] json strings are equal: false
18:03:21,953 INFO  [stdout] json contents are equal: false
18:03:21,953 INFO  [stdout] json contents are equal: -1
18:03:21,954 INFO  [stdout] jsonP contains \n\r: false
18:03:21,954 INFO  [stdout] jsonB contains \n\r: false
```

So there must be something with Json-B string..as json-P output is right.

**Comment by aguibert** [comment]
Can you confirm what versions of Glassfish JSON (JSON-P impl) and Yasson are being used?

I just noticed that with older versions there are newlines between some of the properties. For example with:
```xml
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>1.0.3</version>
</dependency>
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>javax.json</artifactId>
    <version>1.1.2</version>
</dependency>
```
I get:
```
{
    "exception": 
    {
        "message": 
        "foo",
        "type": 
        "java.lang.RuntimeException"
    },
    "finishedAt": 
    "2019-08-21T17:43:30.319Z",
    "startedAt": 
    "2019-08-21T17:43:30.319Z"
}
```

But with newer versions:
```xml
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>1.0.4</version>
</dependency>
<!-- No need to add JSON-P here because it is automatically included as of Yasson 1.0.4 -->
```

I get:
```
{
    "exception": {
        "message": "foo",
        "type": "java.lang.RuntimeException"
    },
    "finishedAt": "2019-08-21T17:46:32.562Z",
    "startedAt": "2019-08-21T17:46:32.562Z"
}
```

**Comment by nimo23** [comment]
I am using (I also looked at the modules-folder of wildfly and updated yasson):

- yasson-1.0.4.jar
- javax.json-1.1.2.jar

But problem still exits..

**Comment by jbescos** [comment]
@nimo23 I tested it with your code and the version 1.0.4 works fine. I'm having the same issue if I run it with 1.0.3.

Lets make one additional check because I don't have experience with Wildfly, but I have seen in other application servers problems with the priority in the class loaders. It could happen that 2 different versions of Yasson are accessible and it is loading the older version.

Could you modify your method:

```
    public static String toJsonByJsonB(Tada tada) {
        try (Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(true))) {
            try(InputStream inputStream = jsonb.getClass().getResourceAsStream("/META-INF/MANIFEST.MF"); Scanner scanner = new Scanner(inputStream)){
                String result = scanner.useDelimiter("\\A").hasNext() ? scanner.next() : "";
                System.out.println(result);
            }
            return jsonb.toJson(tada);
            
        } catch (Exception e) {
            return null;
        }
    }
```
And let us know what does it print. The Yasson version should be displayed.

**Comment by nimo23** [comment]
@jbescos I get this output:

01:39:41,649 INFO  [stdout] Manifest-Version: 1.0
01:39:41,649 INFO  [stdout] Created-By: Apache Maven Bundle Plugin
01:39:41,650 INFO  [stdout] Built-By: default
01:39:41,651 INFO  [stdout] Build-Jdk: 11.0.2
01:39:41,651 INFO  [stdout] Bnd-LastModified: 1567805700364
01:39:41,651 INFO  [stdout] Bundle-Description: Eclipse Yasson. Reference implementation of JSR-367 
01:39:41,652 INFO  [stdout]  (JSON-B).
01:39:41,652 INFO  [stdout] Bundle-DocURL: http://www.oracle.com/
01:39:41,653 INFO  [stdout] Bundle-License: https://projects.eclipse.org/content/eclipse-distributio
01:39:41,653 INFO  [stdout]  n-license-1.0-bsd, https://projects.eclipse.org/content/eclipse-public-
01:39:41,653 INFO  [stdout]  license-1.0
01:39:41,653 INFO  [stdout] Bundle-ManifestVersion: 2
01:39:41,653 INFO  [stdout] Bundle-Name: org.eclipse.yasson
01:39:41,653 INFO  [stdout] Bundle-SymbolicName: yasson
01:39:41,653 INFO  [stdout] Bundle-Vendor: Oracle Corporation
01:39:41,653 INFO  [stdout] Bundle-Version: 1.0.5
01:39:41,653 INFO  [stdout] Export-Package: org.eclipse.yasson;version="1.0.5";uses:="javax.json,jav
01:39:41,653 INFO  [stdout]  ax.json.bind,javax.json.bind.config,javax.json.bind.spi,javax.json.stre
01:39:41,653 INFO  [stdout]  am"
01:39:41,653 INFO  [stdout] Import-Package: javax.enterprise.context.spi;resolution:=optional,javax.
01:39:41,654 INFO  [stdout]  enterprise.inject.spi;resolution:=optional,javax.json;version="[1.1,2)"
01:39:41,654 INFO  [stdout]  ,javax.json.bind;version="[1.0,2)",javax.json.bind.adapter;version="[1.
01:39:41,654 INFO  [stdout]  0,2)",javax.json.bind.annotation;version="[1.0,2)",javax.json.bind.conf
01:39:41,654 INFO  [stdout]  ig;version="[1.0,2)",javax.json.bind.serializer;version="[1.0,2)",javax
01:39:41,654 INFO  [stdout]  .json.bind.spi;version="[1.0,2)",javax.json.spi;version="[1.1,2)",javax
01:39:41,654 INFO  [stdout]  .json.stream;version="[1.1,2)",javax.xml.datatype,javax.naming;resoluti
01:39:41,654 INFO  [stdout]  on:=optional,java.beans;resolution:=optional
01:39:41,654 INFO  [stdout] Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
01:39:41,654 INFO  [stdout] Tool: Bnd-3.5.0.201709291849

**Comment by jbescos** [comment]
@nimo23 I don't see the dependency 'jakarta.json:jakarta.json-api:jar:1.1.5:compile'. That actually contains the class JsonPrettyGeneratorImpl. I hope that is the problem, otherwise I'm running out of ideas because I cannot reproduce it.

You can find that dependency here:
https://mvnrepository.com/artifact/jakarta.json/jakarta.json-api/1.1.5

**Comment by nimo23** [comment]
@jbescos thanks, but I dont see the sense in importing another dependency **by myself** only to have a pretty print enabled by yasson to print my json. I use wildfly and yasson is already included and I am expecting that yasson includes all its needed deps by itself.

**Comment by aguibert** [comment]
I think this issue should be moved to Wildfly, since we have already established that this issue does not occur when running Yasson by itself outside of Yasson.

My suspicion is that the version of Wildfly you are using has an old version of JSON-P (e.g. 1.1.2). The versions of JSONP and JSONB that do not have this issue are 1.1.5 and 1.0.4 respectively.

**Comment by nimo23** [comment]
yes, the version wildfly actually uses is javax.json-1.1.2.
