### ISSUE TITLE
runtime-configuration must have precedence over annotation

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#290]
Annotating a class with

```
@JsonbNillable(value = true)
@JsonbVisibility(value = PrivateFields.class)
public class Item {
..
}
```

and printing the json string with

```
try (Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(true)
				.withNullValues(false)
				.withPropertyVisibilityStrategy(null)
				.withPropertyOrderStrategy(PropertyOrderStrategy.ANY))) {
			return jsonb.toJson(object);
}
```

actually prints the NULL-Values. However, it should **NOT** print the null values, because any runtime-configuration should have precedence over their corresponding annotations. 

**(Tested with org.eclipse.yasson v1.0.4)**

**Comment by aguibert** [comment]
hi @nimo23, where do you see that runtime-configuration should have precedence over annotations?  The runtime configuration with `JsonbConfig` is the "global configuration" and is the broadest scope of configuration. If configuration exists as a smaller scope (e.g. annotation on a class, field, or method) then the smaller scope takes precedence.

From section 4.3 of the spec:
```
If annotations (JsonbNillable or JsonbProperty) on different level apply to the same field (or JavaBean property) or if there is config wide configuration and some annotation (JsonbNillable or JsonbProperty) which apply to the same field (or JavaBean property), the annotation with the smallest scope applies. For example, if there is type level JsonbNillable annotation applied to some class with field which is annotated with JsonbProperty annotation with nillable = false, then JsonbProperty annotation overrides JsonbNillable annotation.
```

**Comment by nimo23** [comment]
Please look at:
`
Global means shared accross attributes/classes, local is the opposite so annotations are clearly local and jsonbconfig global IMHO. In all cases, config must override what is hardcoded for flexibility reasons.`

Issue should be reopened.

**Comment by aguibert** [comment]
I'm not sure if Romain was agreeing with you or disagreeing with you over on eclipse-ee4j/jsonb-api#169 =)

We can discuss more over on that issue though, and if we determine the spec/TCK says otherwise then we can change Yasson

**Comment by bravehorsie** [comment]
Which configuration has precedence is defined by the specification. Generally smaller scope have precedence over larger one.

**Comment by nimo23** [comment]
>In all cases, config must override what is hardcoded for flexibility reasons.

This is what the spec implicitly says.
