### ISSUE TITLE
Deserialization from null to JsonValue

### ISSUE THREAD

**Issue by leadpony** [eclipse-ee4j/yasson#293]
First of all, thanks everyone for developing such a nice software.

I have a class to be instantiated from JSON.
```java
public class Stuff {
    public int a;
    public JsonValue b;
}
```
And the input JSON for `Jsonb#fromJson() `is here:
```json
{
    "a": 42,
    "b": null
}
```
I expected the value of `Stuff#b` should be `JsonValue.NULL` because the target type is `JsonValue`. However I got just a `null` of Java as the value of the member instead. 
Is this intended behavior?

**Comment by aguibert** [comment]
hi @leadpony, thanks for raising this question.

Here is the relevant portion of the JSON-B spec:

> ## 3.14.1 Null Java field
> The result of serializing a java field with a null value is the absence of the property in the resulting JSON document.
>
> The deserialization operation of a property absent in JSON document MUST not set the value of the field, the setter (if available) MUST not be called, and thus original value of the field MUST be preserved.
>
> The deserialization operation of a property with a null value in a JSON document MUST set the value of the field to null value (or call setter with null value if setter is present). The exception is java.util.Optional, OptionalInt, OptionalLong, OptionalDouble instances. In this case the value of the field is set to an empty optional value.

So according to the spec the value should indeed be `null`, and the only types that get special consideration are the various forms of `Optional`.

That being said, it does seem reasonable to include `JsonValue` in the list of types that get special handling, and have their value set to `JsonValue.NULL` as you suggest. Do you want to [raise this issue over at the JSON-B spec repo](https://github.com/eclipse-ee4j/jsonb-api/issues/new) so we can consider it for the next version of JSON-B?

**Comment by leadpony** [comment]
@aguibert 
Great!, thank you. I will raise an issue at the API.
