### ISSUE TITLE
Include property name that failed to serialize in error messages

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#297]
**I get this error:**

`SEVERE [org.eclipse.yasson.internal.Marshaller] double value cannot be Infinite or NaN`

Please include the **"property name"** in this error message which makes the trouble. It's a mess to search for that property manually.

**Comment by aguibert** [comment]
hi @nimo23, what version of Yasson are you using here? I thought in Yasson 1.0.4 I did add logging to include the property name that failed.

Also, in PR #295 we're going a step farther and also including the value in addition to the property name.

**Comment by aguibert** [comment]
ah, I see the problem. We only include the property name that failed for the deserialization process, but not the serialization process. This should be fixed

**Comment by nimo23** [comment]
ok thanks! I am actually using **yasson v1.0.4**.
