### ISSUE TITLE
@JsonbCreator-annotated inaccessible constructors shouldn't overrule no-arg constructor

### ISSUE THREAD

**Issue by JohT** [eclipse-ee4j/yasson#326]
As mentioned in [yasson/pull/280](https://github.com/eclipse-ee4j/yasson/pull/280)
and shown by the currently ignored unit test method 
"AnnotationIntrospectorTest.testNoArgConstructorShouldBePreferredOverUnusableJsonbAnnotatedProtectedConstructor",
inaccessible constructors lead to an error, even if there is also an valid standard no-arg constructor. 

This is a cause of using "creators" (e.g. constructors) if they exist, 
even if they can't be used at the end.

I guess, this is something to discuss, since the specification seems not to be that clear IMO, how it "should" be.

**Comment by m0mus** [comment]
Yes, I agree that the spec is bit loose in this area. We are currently collecting suggestions for JSONB.next in JSONB API [issues tracker](https://github.com/eclipse-ee4j/jsonb-api/issues). Feel free to make your suggestions there.

**Comment by aguibert** [comment]
Dmitry is right that this should be considered at the spec level. I've adjusted this spec-level issue to also include what is being asked for here:
https://github.com/eclipse-ee4j/jsonb-api/issues/61
