### ISSUE TITLE
ZonedDateTime uses ObjectDeserializer 

### ISSUE THREAD

**Issue by Celludriel** [eclipse-ee4j/yasson#328]
Hey, 

Consider following code:

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

```
<!-- JSON -->
<!-- JSON-P API -->
<dependency>
	<groupId>javax.json</groupId>
	<artifactId>javax.json-api</artifactId>
	<version>1.1</version>
</dependency>

<!-- JSON-P RI -->
<dependency>
	<groupId>org.glassfish</groupId>
	<artifactId>javax.json</artifactId>
	<version>1.1</version>
	<scope>runtime</scope>
</dependency>

<!-- JSON-B API -->
<dependency>
	<groupId>javax.json.bind</groupId>
	<artifactId>javax.json.bind-api</artifactId>
	<version>1.0</version>
</dependency>

<!-- Yasson (JSON-B RI) -->
<dependency>
	<groupId>org.eclipse</groupId>
	<artifactId>yasson</artifactId>
	<version>1.0.4</version>
	<scope>runtime</scope>
</dependency>
```

```
public class TestJson implements JsonObject {

    @JsonbDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")
    private ZonedDateTime zonedDateTime;

    public ZonedDateTime getZonedDateTime() {
        return zonedDateTime;
    }

    public void setZonedDateTime(ZonedDateTime zonedDateTime) {
        this.zonedDateTime = zonedDateTime;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        TestJson testJson = (TestJson) o;

        return new EqualsBuilder()
                .append(getZonedDateTime(), testJson.getZonedDateTime())
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(getZonedDateTime())
                .toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("zonedDateTime", zonedDateTime)
                .toString();
    }
}

public class DateFormatTest {

    private JsonMapper jsonMapper = new JsonMapper();

    @Test
    public void dateFormatTest(){
        TestJson testJson = new TestJson();

        LocalDateTime ldt = LocalDateTime.of(2016, Month.AUGUST, 22, 14, 30);
        ZonedDateTime klDateTime = ldt.atZone(ZoneId.of("Europe/Paris"));

        testJson.setZonedDateTime(klDateTime);

        String result = jsonMapper.toJSON(testJson);

        System.out.println(result);

        TestJson afterRemarshal = jsonMapper.toObjectFromJSON(TestJson.class, result);

        Assertions.assertThat(testJson).isEqualTo(afterRemarshal);
    }
}
```

You would expect that after you serialize and deserialize both results would be the same.  However the result is:

`
org.junit.ComparisonFailure: 
Expected :be.delijn.test.TestJson@3003697[zonedDateTime=2016-08-22T14:30Z[UTC]]
Actual   :be.delijn.test.TestJson@4e41089d[zonedDateTime=2016-08-22T14:30+02:00[Europe/Paris]]
`

After debugging I found out that he is using ObjectDeserializer instead of what I assumed had to be DateTypeDeserializer.java.

Is this expected behavior or a bug and how can we fix it that this test would work.  Do we need to write our own custom Deserializer ?

**Comment by Verdent** [comment]
Hi @Celludriel,

I have to say, that I am a bit confused about your example here. For example JsonMapper is not in this project at all. But anyway I have done some rework to your example and found out that you need to add VV at the end of your formatting String. It adds the exact Zone name. It should look like this after the change `@JsonbDateFormat("yyyy-MM-dd'T'HH:mm:ssZVV")`

Let me know if it works as expected now :-)

**Comment by Celludriel** [comment]
Hey @Verdent 

Apologies, I didn't notice JsonMapper is my helper class to do some of the basic work.  It totally slipped my sight.

I'm home from work now , I'll try it first thing on monday and give you an answer

**Comment by Verdent** [comment]
Not a bug.

**Comment by Verdent** [comment]
No worries :-) I am glad I could help.
