### ISSUE TITLE
Checkstyle plugin

### ISSUE THREAD

**Issue by Verdent** [eclipse-ee4j/yasson#341]
I was thinking about adding maven-checkstyle-plugin to yasson and I was wondering about our requirements here. Basically which checks we want to be included.

I was thinking about following:
-  Charset -> UTF-8
- Line separator -> lf
- Javadoc on methods
- Naming conventions for methods, fields, classes etc.
- Avoid star imports
- Unused/redundant imports
- Illegal imports (such as sun.*)
- Left curly bracket -> on the same line as method, if, class etc.
- Right curly bracket -> alone on the line
- Allow single line statement ( if(1>2) return something; )
- Do not allow statement without {} on the new line ( if (1>2) \n return something; )
- Do not allow empty loop body
- Indentation -> 4 chars
- Max line length -> 130?
- Max method lines -> 150?
- Max method parameters -> 7?
- Do not allow multiple variable declaration on the same line
- One statement per line
- File name have to match name of the class
- More or less all of whitespace handling options -> http://checkstyle.sf.net/config_whitespace.html
- Modifier order -> https://checkstyle.sourceforge.io/config_modifier.html#ModifierOrder
- Redundant modifier -> https://checkstyle.sourceforge.io/config_modifier.html#RedundantModifier
- Checks that classes that either override equals() or hashCode() also overrides the other. 
- Incorrect boolean checks ->  if (b == true), b || true, !false, etc. 
- Incorrect boolean returns
- Utility classes does not have public constructor
- TODO comments
- Check for case statements without break, return etc.
- No trailing whitespaces

And possibly:
- Import ordering

What do you think @aguibert ?

Please check another settings if interested here: https://checkstyle.sourceforge.io/

**Comment by aguibert** [comment]
TBH I haven't had much issue with code formatting in the Yasson codebase (most of which I did not write). If you want, we can enable some checkstyle rules, but I'd like to keep out any pedantic checks such as:
- Javadoc on methods --> shouldn't have to javadoc internal/private methods
- Naming conventions for methods, fields, classes etc. --> this can be caught at code review time
- Max line length
- Max method lines
- Max method parameters
- No trailing whitespaces --> I see no need to enforce this
- Import ordering --> I see no need to enforce this

**Comment by Verdent** [comment]
Well the reason behind this for me is more or less just as a prevention. It sometimes finds some incorrectly formatted or forgotten lines of code and it helps to keep codebase format in track. I wouldn't say that it is bad thing to have.

- Javadoc on methods -> yes definitely only on public. I would even consider it to enforce it anywhere else.
- Naming  conventions -> I just wanted something automated to tell you that you have something incorrect there in the name. Then you can fix it even before code review. 
- Max line length
- Max method lines
- Max method parameters -> These three there could improve readability of the methods. But I guess it is more or less just nice to have from my point of view so we can ignore those :-)
- No trailing whitespaces -> I have no problem with not including this one.
- Import ordering -> I have no problem with not including this one.
