### ISSUE TITLE
JsonBindingProvider not a subtype

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#353]
I get the following runtime error sporadically and I dont know the reason. Many times it works, sometimes this error is shown (this is the **whole** stacktrace):

`
java.lang.RuntimeException:java.util.ServiceConfigurationError:javax.json.bind.spi.JsonbProvider:org.eclipse.yasson.JsonBindingProvider not a subtype`

**Comment by aguibert** [comment]
hi @nimo23, usually I've seen errors like this when there is a classloader conflict of some sort. For example, 2 copies of JSON-B API being loaded from 2 different classloaders. Double check your maven dependencies and ensure that you aren't pulling in 2 copies of `javax.json.bind` anywhere, or if you're running in an app server check to see if the app server is providing 1 copy and you also have 1 copy packaged inside your ear/war.

**Comment by nimo23** [comment]
Thanks. Error is gone after rebuild.
