### ISSUE TITLE
When PropertyNamingStrategy is specified, properties may not be printed.

### ISSUE THREAD

**Issue by aguibert** [eclipse-ee4j/yasson#371]
@Empressia commented on [Thu Dec 05 2019](https://github.com/eclipse-ee4j/jsonb-api/issues/212)

Payara Micro 5.194（JDK11）でJAX-RSを使用しているときに、  
Json-BのPropertyNamingStrategyを指定したら、  
オブジェクトのプロパティがシリアライズされませんでした。  

テストコードを書きました。  
https://github.com/Empressia/JsonBTest01  
https://github.com/Empressia/JsonBTest01/blob/master/src/test/java/jp/empressia/test/jsonb/JsonBTest01.java  

シリアライズしたクラス：  
```java
	public static class SomethingClass {
		@SuppressWarnings("unused")
		private String Subject = "Field";
		public String getSubject() {
			return "Getter";
		}
	}
```
↓
テスト結果：  
```
Expected: is "{\"Subject\":\"Getter\"}"
     but: was "{}"
```

フィールドを削除するとテストは通ります。

**Comment by Degubi** [comment]
Tested with current version, was unable to reproduce.
Tested with 1.0.5, unable to reproduce.
Tested with 1.0.4 (same version as the error reporter had) and the error happens there.
Not sure what change fixed this, but it got fixed between 1.0.4 and 1.0.5

Test code:
```java
public class Issue371 {
    
    @Test
    public void runTest() {
        JsonbConfig config = new JsonbConfig().withPropertyNamingStrategy(PropertyNamingStrategy.UPPER_CAMEL_CASE);
        Jsonb jsonb = JsonbBuilder.newBuilder().withConfig(config).build();

        String jsonString = jsonb.toJson(new SomethingClass());
        
        assertEquals("{\"Subject\":\"Getter\"}", jsonString);
    }
    
    public static class SomethingClass {
        @SuppressWarnings("unused")
        private String Subject = "Field";
        public String getSubject() {
            return "Getter";
        }
    }
}
```

**Comment by aguibert** [comment]
Thanks for testing this one out @Degubi. It looks like this bug report is a duplicate of #296 which has been fixed in 1.0.5 as you indicated
