### ISSUE TITLE
Generating incomplete JSON: too less information

### ISSUE THREAD

**Issue by nimo23** [eclipse-ee4j/yasson#380]
**Describe the bug**
I get a not informative SEVERE message from yasson:

`19:42:23,183 SEVERE [org.eclipse.yasson.internal.Marshaller] Generating incomplete JSON`

Not more information is given in the log by yasson. I call that json processing with:

```
try (Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(withFormatting)
.withNullValues(withNullValues)
.withPropertyVisibilityStrategy(new PrivateVisibilityStrategy()))) {
return jsonb.toJson(object);} 
catch (Exception e) {
// this is NOT called
log.error("Error to convert to json: ", e);
return null;
}
```

The Exception-block is NOT called, because yasson logs it as SEVERE and does not throw an exception.

**Expected behavior**
More information about why JSON generation is incomplete so user can find the issue easier.

**System information:**
 - Java Version: 12
 - Yasson Version: 1.0.5

**Comment by nimo23** [comment]
I checked to parse exactly the same instance by jackson with 

```
return mapper.writeValueAsString(o);
```

and it returns without problems, I did even not included any jackson annotations on that intance - it works. But yasson is not able to create the json with the same instance, the only hint I get is this sentence:

`19:42:23,183 SEVERE [org.eclipse.yasson.internal.Marshaller] Generating incomplete JSON`

**Comment by aguibert** [comment]
hi, can you include an example of the Object you are attempting to convert to JSON so we can reproduce the issue?

Also, the error `Generating incomplete JSON` must be coming from this line:
https://github.com/eclipse-ee4j/yasson/blob/1.0.5/src/main/java/org/eclipse/yasson/internal/Marshaller.java#L89

**Comment by nimo23** [comment]
I try to find the error and let you know. 

In the meantime, would it be better to throw the error instead of hiding it from the user?

```
} finally {
            try {
                if (close) {
                    jsonGenerator.close();
                }
            } catch (JsonGenerationException jge) {
                logger.severe(jge.getMessage());
                // throw error, instead hiding
                throw jge;
            }
        }
```

Yasson not only produces an _incomplete_ json but nothing, so throwing an error would be better in this case, because yasson did not produce anything.

**Comment by aguibert** [comment]
yea, I agree that throwing an exception seems preferable here. But I'd need to reproduce the issue for myself and do more investigation to be certain

**Comment by nimo23** [comment]
I found the property which leads to this error. It was not easy because I overlooked the property within an **abstract** class. All its subclasses inherited the `log`-method which cannot and should never be (de)serialized:

```
public abstract class AbstractItem {

        // this was the reason for: "Generating incomplete JSON"
	protected final Logger log = Logger.getLogger(getClass()); 
..
}
```
I annotated the property with `@JsonbTransient` and now it works.
Please make sure that yasson always bypass the logging classes. It makes no sense to try to (de)serialize it. It would also helpful to throw the error so users can look at which field the (de)serializing failed.

**Comment by nimo23** [comment]
It is also a little related to this:
https://github.com/eclipse-ee4j/yasson/issues/305

But in this case, the stacktrace shown in the other issue is not shown in this issue.

**Comment by aguibert** [comment]
The fix for issue #305 was included in Yasson 1.0.6, and you are on 1.0.5. Does upgrading to 1.0.6 fix the problem?

**Comment by nimo23** [comment]
@aguibert yes, I upgraded to 1.0.6 and it now shows a better message:

`Caused by: javax.json.bind.JsonbException: Unable to serialize property 'log' from ...`

So I will close this issue. Thanks.

**Comment by joaomarcos-dev** [comment]
I'm getting the same error. Even though the deserialization occurs, the serialization generate this error.

dez. 20, 2020 6:15:39 PM org.eclipse.yasson.internal.Marshaller marshall
SEVERE: Unable to serialize property 'address' from com.negociodacidade.apirest.resource.pojo.CompanyPagePojo
dez. 20, 2020 6:15:39 PM org.eclipse.yasson.internal.Marshaller marshall
SEVERE: Generating incomplete JSON 

All the others properties from CompanyPagePojo got serialized when I put @JsonbTransient in the 'address' property which is a non primitive value nor a collection, just a simple pojo. Even the collections List<String> are serialized without problems. 
I didn't get the solution yet
