### ISSUE TITLE
Recursive reference on serializing root object

### ISSUE THREAD

**Issue by johnrodey** [eclipse-ee4j/yasson#383]
This is in relation to a previous bug: https://github.com/eclipse-ee4j/yasson/issues/187

I too have experienced this problem. Previously (running 2.27) this code would print the root document, however oddly it would only work once if I reused the Jsonb object. Recreating those objects each time is expensive so I updated to the latest (2.30) hoping to fix that and now the same code results in this 'Recursive reference has been found' issue. If this is expected behavior is there a means to printing the root element in the serialized JSON without changing the pojo's structure?  Is it possible to provide a new sample since the previous sample that did something similar to my snippet is no longer valid?

Below is some trimmed down sample code to reproduce:

```
public class CustomSerializer implements JsonbSerializer<SAMPLE> {
	public CustomSerializer() {}
	@Override
	public void serialize(final SAMPLE p, final JsonGenerator g, final SerializationContext c) {
		g.writeStartObject();
		c.serialize(p.getClass().getSimpleName(), p, g);
		g.writeEnd();
	}
}
```
My object to be serialized:

```
@JsonbTypeSerializer(CustomSerializer.class)
public class SAMPLE {
	private String id;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
}
```
I'm looking to get the output:

```
{
    "SAMPLE": {
	"id":1
    }
}
```

**Comment by aguibert** [comment]
hi @johnrodey, we are planning to address this feature in the next version of the JSON-B spec in two ways:

1. Allow for polymorphic [de]serialization: https://github.com/eclipse-ee4j/jsonb-api/issues/147
2. Allow for programmatic customization of a class: https://github.com/eclipse-ee4j/jsonb-api/issues/88

Between these two issues what you are trying to do will be possible. But for now, with the current version of JSON-B/Yasson there is not a way to achieve what you are trying to accomplish.
