### ISSUE TITLE
Cryptic error on primitive null

### ISSUE THREAD

**Issue by triceo** [eclipse-ee4j/yasson#399]
**Describe the bug**
When a primitive field (such as `boolean`) is null, Yasson gives a very cryptic message which gives no hints as to what or where is wrong.

**To Reproduce**

Consider the following simplified class definition:

    class SomeClass {

        @JsonbProperty(nillable = true)
        private Boolean someBoolean;
   
        void setSomeBoolean(boolean value) { // note that value is a primitive boolean
            // leaving this empty, exception will be thrown before Yasson gets here.
        }

    }

Now assume that the JSON being deserialized has `null` for `someBoolean`. This is clearly an issue, as `boolean` does not accept `null` as a value. (Only `Boolean` does.) Unfortunately, Yasson does not tell you that. Instead, you get this:

    javax.json.bind.JsonbException: Internal error: null

	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:66)
	...

**Expected behavior**
At the very least, I would expect the exception to be rethrown with a descriptive message pointing out the problem. What was being deserialized (class, field) and what happened.

**System information:**
 - OS: Fedora Linux.
 - Java Version: 11, but it doesn't really matter.
 - Yasson Version: 1.0.7.

**Comment by Degubi** [comment]
Using this code
```java
public final class Main {
    public static class SomeClass {

        @JsonbProperty(nillable = true)
        private Boolean someBoolean;

        void setSomeBoolean(boolean value) { // note that value is a primitive boolean
            // leaving this empty, exception will be thrown before Yasson gets here.
        }
    }
    
    public static void main(String[] args) {
        var jsonb = JsonbBuilder.create();
        
        var input = "{\"someBoolean\": null}";
        var deserialized = jsonb.fromJson(input, SomeClass.class);
    
        System.out.println("Some: " + deserialized.someBoolean);
    }
}
```

I got this as output without errors: 'Some: null'.
Did I do something differently? I might have misunderstood something @triceo
