### ISSUE TITLE
JSON-B / Yasson is ignoring the new JsonbConfig :: withDeserializers

### ISSUE THREAD

**Issue by lusabo** [eclipse-ee4j/yasson#406]
I am migrating a project from Jackson to Json-B (Yasson v. 1.0.7), and the code below is to ilustrate a scenario that is ocurring with me.

I have a json file like this:

    {
      "response": {
        "accessories": {
          "accessory": [
            {
              "finance": "mandatory",
              "type": "INDIVIDUAL"
            },
            {
              "finance": "optional",
              "type": "ORIGINAL"
            },
            {
              "finance": "not",
              "type": "TRADE"
            }
          ]
        }
      }
    }

I am rewriting one test like below:

    @Test
    public void testDeserialize() {

        final JsonbConfig config = new JsonbConfig()
                .withSerializers(new MySerializer())
                .withDeserializers(new MyDeserializer());

        final Jsonb jsonb = JsonbBuilder.create(config);

        final InputStream data = this.getClass().getClassLoader().getResourceAsStream("response.json");

        final Response obj = jsonb.fromJson(data, Response.class);

        final Accessories accessories = obj.getAccessories();

        assertThat(accessories.getAccessory().isEmpty(), is(false));
    }
	
The code of the class MyDeserializer is:
```
public class MyDeserializer implements JsonbDeserializer<FType> {
    @Override
    public FType deserialize(JsonParser parser, DeserializationContext context, Type type) {
        return FType.MANDATORY;
    }
}
```

The problem is when I run the test the deseralizator is not called and the property **accessory** from object **obj** is null.

How to solve it?

**Comment by aguibert** [comment]
hi @lusabo, can you please include your model objects such as `Response` and `Accessories`?

**Comment by lusabo** [comment]
Hi @aguibert ,

I discovered my problem, I don't know how Yasson can help at this point. It was missing a set method of an attribute which is of type List in one of the entities. The problem is that these entities are generated by JAXB and it seems that JAXB does not generate setters for List type properties.

**Comment by aguibert** [comment]
have you tried using a custom `JsonbAdapter` implementation? The adapter may be used to perform "manual" conversion logic for situations like this where you can't control the model class (e.g. JAX-B model) and they don't match the getter/setter pattern.

See: http://json-b.net/docs/user-guide.html#adapters

**Comment by lusabo** [comment]
Yes, I tried with Adapter too, now I solving configuring the XJC (JAXB2) plugin to generate my stubs with the setters.

**Comment by lusabo** [comment]
Hi @aguibert ,

I managed to get the plugin to generate the stubs with the setters for attributes of List type .

For historical record only, the problem was solved by adding the following arguments:
```
<args>
                                 <arg> -Xsetters </arg>
                                 <arg> -Xsetters-mode = direct </arg>
                                 <arg> -XtoString </arg>
                             </args>
```

I don't know if this problem will be solved by Yasson, if so, I don't know how to proceed with the issue, otherwise, you can close it.

**Comment by aguibert** [comment]
can you clarify what the problem is at this point? I've lost track. Is it still the same problem as the OP or has it changed? If it's the same problem as the OP, you'll need to upload the additional info I asked for.

**Comment by lusabo** [comment]
We are migrating a project that uses Jackson to use Json-b / Yasson. A part of this project uses JAXB to generate some classes (stubs). Another part of the project uses these classes, and when serializing/deserializing with my serializers / deserializers (I also tested adapters) I was having problems with one of them that has one of its List <Enum> attributes. When deserializing a json file (as shown at the beginning), the field was null, and when debugging I realized that the class that had the list did not have the set method for this list, which by JSON-B is not possible to deserialize an entity without get and set methods.

**Comment by aguibert** [comment]
> The question is, is json-b going to force all entities to have set and get methods for their attributes?

For the default mapping, yes getters/setters (or public field) are required.

If it is not possible to have these, then "custom mapping" may be used, which is when you implement custom Serializer/Deserializer/Adapter classes.

**Comment by aguibert** [comment]
haven't seen any additional activity on this question so I'm going to close out. We can re-open if needed
