### ISSUE TITLE
Support java.beans.Transient?

### ISSUE THREAD

**Issue by onacit** [eclipse-ee4j/yasson#441]
I know this is not what an implementation should concern.

But someone please issue to any spec guy for supporting the `java.beans.Transient`.

I know `JsonbTransient` works for that.

```java
    // should not be serialized/deserialized
    //@jakarta.json.bind.annotation.JsonbTransient
    @java.beans.Transient
    public String getSomeHuh() {
        return some + ", huh?";
    }

    private String some;
```

**Comment by aguibert** [comment]
Issue moved to [eclipse-ee4j/jsonb-api #253](https://github.com/eclipse-ee4j/jsonb-api/issues/253) via [**ZenHub**](https://www.zenhub.com/)
