### ISSUE TITLE
Wrong serialized name and ignored field annotations when second letter is capital

### ISSUE THREAD

**Issue by dusik66** [eclipse-ee4j/yasson#443]
When the name of the field has second character capital, than serialized name of the field is ignored. Also annotations on the field are ignored. 

**To Reproduce**
String aBc;

Output will be {“ABc”: “value”}

**Expected behavior**
Output should be {“aBc”: “value”}

Mistake is in the ClassParser.toPropertyMethod() and in ClassParser.lowerFirstLetter()

**System information:**
 - OS: [Windows]
 - Java Version: [11]
 - Yasson Version: [1.0.7]

**Comment by Degubi** [comment]
Same, can't reproduce on 2.0.1. All annotations are working and the output is:
{"aBc":"value"}

**Comment by Verdent** [comment]
Hi @dusik66 , could you please provide reproducer if this issue is still valid for you?

**Comment by dusik66** [comment]
Hi, I have found that Lombok cause the problem:

```
import lombok.Data;

import javax.json.bind.Jsonb;
import javax.json.bind.JsonbBuilder;

public class App {
    public static void main(String[] args) {
        Dog dog = new Dog();
        dog.aBc = "value";

        Jsonb jsonb = JsonbBuilder.create();
        String result = jsonb.toJson(dog);
        System.out.println(result);
    }

    @Data
    public static class Dog {
        private String aBc;
    }
}
```

output:
```
{"ABc":"value"}
```

**Comment by Verdent** [comment]
Alright so if I am getting this right, it is not an issue at our side? :-)

**Comment by dbaldes** [comment]
I just ran into the same issue. I sort of agree that lombok "causes" it, but I think it would be immensely useful if yasson could handle this - considering that a) lombok is quite popular, and b) it behaves correctly by generating getABc() from the property name "aBc". The property "aBc" is the property that belongs to the getter getABc(), but in this case, the annotations on aBc don't apply - that is not what I would expect.
