### ISSUE TITLE
Missing artifact with 2.0.0

### ISSUE THREAD

**Issue by Degubi** [eclipse-ee4j/yasson#448]
Getting a 'Missing artifact org.eclipse:yasson:jar:2.0.0' error when trying to use the latest version released 23 days ago.

After looking at https://mvnrepository.com/artifact/org.eclipse/yasson there's no 2.0.0 version listed, only 2.0.0-M2
@m0mus

**Comment by aguibert** [comment]
I checked with @m0mus on this and he said there is still some additional process to be passed before it is officially released. See here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=567135
