### ISSUE TITLE
inconsistent generating incomplete JSON error

### ISSUE THREAD

**Issue by dannyb2018** [eclipse-ee4j/yasson#475]
I have a very simple servlet that turns a pojo into a json string.  It works on windows 10, it works on docker on windows 10 using WSL 2.  If i try to run the exact same image on docker on linux it prints out this rather unhelpful error with zero other information

**To Reproduce**
```
QPJsonDashboard.java
public class QPJsonDashboard
{
    public QPJsonToolbar toolbar = new QPJsonToolbar();
    public QPJsonView view = null;
    public String textColour;
    public String backgroundColour;
}

QPJsonToolbar.java
public class QPJsonToolbar
{
    public String avatar = null;
    public List<QPJsonMenuItem> toolbarButtons = new ArrayList<>();
}

QPJsonMenuItem.java
public class QPJsonMenuItem
{
    public String icon;
    public String tooltipText;
    public String route;    
    public String componentName;
}
QPJsonView.java
public class QPJsonView
{
    public QPJsonSideMenu sideMenu = null;
    public QPJsonPage landingPage = null;
}
QPJsonSideMenu.java
public class QPJsonSideMenu
{
    public String name;
    public List<QPJsonMenuItem> menuItems = new ArrayList<>();
}
QPJsonPage.java
public class QPJsonPage
{
    public String componentName = null;
}

QPDashboard.java
@Path("/dashboard")
public class QPDashboard extends HttpServlet
{
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getUserDashboard(@Context HttpServletRequest httpRequest)
    {
        Response response = null;
        try
        {
            JsonbConfig jsonbConfig = new JsonbConfig()
                                      .withPropertyNamingStrategy(PropertyNamingStrategy.LOWER_CASE_WITH_UNDERSCORES)
                                      .withNullValues(true)
                                      .withFormatting(false);

            Jsonb jsonb = JsonbBuilder.create(jsonbConfig);


            // Make the dashboard upon landing
            QPJsonDashboard instance = new QPJsonDashboard();

            // Set the colours
            instance.backgroundColour = "cpta-blue-grey";
            instance.textColour = "cpta-gold";

            // Make the toolbar
            instance.toolbar = new QPJsonToolbar();
            // Set the user avatar
            instance.toolbar.avatar = "https://avatars3.githubusercontent.com/u/39492136?s=460&v=4";
            // Add the buttons
            // First do the general overview
            QPJsonMenuItem item = new QPJsonMenuItem();
            item.icon = "mdi-pipe-wrench";
            item.tooltipText = "Quick Start";
            item.route="/general";
            item.componentName="qp-general-view";
            instance.toolbar.toolbarButtons.add(item);

            String json = jsonb.toJson(instance);

            response = Response.ok().entity(json).build();
        }
        catch(Exception E)
        {
            E.printStackTrace();
        }
        // The workspace is made up of 
        return response;
    }
}
```

**Expected behavior**
I would expect the output of a call to that url to be:
`{"background_colour":"cpta-blue-grey","text_colour":"cpta-gold","toolbar":{"avatar":"https://avatars3.githubusercontent.com/u/39492136?s=460&v=4","toolbar_buttons":[{"component_name":"qp-general-view","icon":"mdi-pipe-wrench","route":"/general","tooltip_text":"Quick Start"}]},"view":null}`

Or at least a stack trace after an exception is thrown but it dies at this line
`            String json = jsonb.toJson(instance);`
and i see a SEVERE: generating incomplete JSON error.

**System information:**
 - OS: [e.g. Linux, Windows, Mac]
 - **works on**
 - Windows 10 - 19042.746
 - JRE 11.0.6
 - docker 20.10
 - yasson 1.0.8
 - running in jetty 9.4.31.v20200723
 
**does not work on**
linux ubuntu 18.04.5LTS
JRE 11.0.6
docker 10.3
yasson 1.0.8

The images are built on windows saved moved to the ubuntu machine loaded and containers built, so what is running in both should be identical.  

**I think i am not the only person to mention that this error message is completely useless, could you at least throw an exception so their might be a hint at what the problem is**

**Comment by jbescos** [comment]
I have tried your example without the layer of jax-rs, with Yasson 1.0.8 and 2.0.1 and I get the expected JSON. I am running it in:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

```
Could you try it in newer Yasson version?. For example 2.0.1.

In case docker is not printing the stederr properly, if you add this in your code do you see the stack trace?:
```
try {
 throw new IllegalArgumentException("I want to see this stack trace");
} catch (IllegalArgumentException e) {
 e.printStackTrace();
}
```

**Comment by dannyb2018** [comment]
Hi,

Thanks for your prompt reply.  

**The error was an inconsistent javaee-api version.  The version of yasson 1.0.4 and 1.0.8 both require javaee-api 8 and one part of the application had 7 and another 8.**  

No idea why it was a problem in **docker** on linux but not on windows.  stderr was printing ok, looking at the code it looks like you are throwing an exception now but it didnt print.  Not sure how to stop this problem coming up again but you might see it in people using JEE containers so am leaving here in case anyone has the same problem.

Thank you again
