### ISSUE TITLE
Support for YearMonth Serialization

### ISSUE THREAD

**Issue by thatsIch** [eclipse-ee4j/yasson#486]
**Is your feature request related to a problem? Please describe.**
Yasson supports `java.time.*`-classes like `LocalDateTime` but is missing support for `YearMonth` (and `MonthDay` as a matter of fact) 

**Describe the solution you'd like**
The yasson-package [org.eclipse.yasson.internal.serializer](https://github.com/eclipse-ee4j/yasson/tree/master/src/main/java/org/eclipse/yasson/internal/serializer) should contain:

* `YearMonthSerializer`
* `YearMonthDeserializer`

which allows allowing following use-case

```java
class YearMonthWrapper {
    public YearMonth yearMonth;
}

class Main {
    public static void main(String[] args) {
        Jsonb jsonb = JsonbBuilder.create();
        YearMonthWrapper wrapper = new YearMonthWrapper();
        wrapper.yearMonth = YearMonth.of(2021, Month.April);

        String serializationResult = jsonb.toJson(wrapper);
        YearMonthWrapper deserializationResult = jsonb.fromJson(serializationResult, YearMonthWrapper.class);
    }
}
```

**Comment by Verdent** [comment]
Hi @thatsIch , thank you for this suggestion. I think it does make sense to add this support. :-) I will take a look at that.
