### ISSUE TITLE
Add built-in Record  type support

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/yasson#495]
Currently, to make `Record` work with JSONB needs extra config.  

https://github.com/hantsy/java-sandbox/blob/master/record/src/main/java/com/example/demo/JsonbExample.java

I think it should be supported,  although the latest Jakarta EE 10 APIs targets Java 11. But it should not reject the newest Java syntax.

**Comment by Thihup** [comment]
Any updates?

**Comment by Verdent** [comment]
Oh, I forgot to link the issue :-) I just need to update testing pipelines because of this PR a bit. and after that I will merge it

**Comment by Verdent** [comment]
PR with this change merged
