### ISSUE TITLE
SerializationContext in custom JsonbSerializer won't call other custom serializers

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [eclipse-ee4j/yasson#497]
**Describe the bug**
Hello,

I was experimenting with some custom serializers in a Payara-based Jakarta EE application and found out that I am unable to call other registered custom serializers, at least in my particular case. I've mostly found out why, but I am not sure this is actually a bug or an intended behaviour.

In short, when one calls a **SerializationContext.serialize()** on an object that happens to have a custom serializer registered AND a default one, it will call the default one and not the registered. In my particular case, it was a **LocalDateTime** custom serializer that was bypassed in favour of the default one. I will explain in the details.

**To Reproduce**

I have created a simple LocalDateTime serializer because I wanted to write it to JSON as a number, in milliseconds (default writes it as String).

```
public class LocalDateTimeToMillisSerializer implements JsonbSerializer<LocalDateTime> {

    @Override
    public void serialize(LocalDateTime dateToSerialize, JsonGenerator generator, SerializationContext ctx) {

        if (dateToSerialize != null) {
            generator.write(dateToSerialize.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli());
        } else {
            generator.writeNull();
        }
    }
}
```
And in my application, I have registered it as JSON config to be applied globally.

```
@Provider
@Produces(MediaType.APPLICATION_JSON)
public class JSONBConfigurator implements ContextResolver<Jsonb> {

    @Override
    public Jsonb getContext(Class<?> type) {

        return JsonbBuilder.newBuilder()
            .withConfig(createConfiguration())
            .build();

    }

    private JsonbConfig createConfiguration() {
        return new JsonbConfig()
            .withSerializers(new DateToMillisSerializer(), new LocalDateTimeToMillisSerializer(), new PairSerializer())
            .withNullValues(true)
            .withDateFormat(JsonbDateFormat.TIME_IN_MILLIS, Locale.getDefault());
    }
}
```
This Provider is naturally registered in the JAXRS Application class, as a Singleton.

Then I decided I wanted a new one for a **Google Guava** class called **Pair**. 
This is useful to quickly build a JSON response without an object. I used to use Jackson before JSONB/Yasson was a thing and this worked fine. It prints a simple JSON object with the key and the value.
Since there is currently no dedicated JsonbSerializer for this class, Yasson ends up printing an object with all its variables (I would say this is standard behaviour). 
So I coded this:

```
public class PairSerializer implements JsonbSerializer<Pair> {

    @Override
    public void serialize(Pair obj, JsonGenerator generator, SerializationContext ctx) {

        if (obj != null) {
            generator.writeStartObject();
            generator.writeKey(obj.getLeft().toString());
            ctx.serialize(obj.getRight(), generator); // HERE
            generator.writeEnd();
        } else {
            generator.writeNull();
        }
    }
}
```
You will notice that they were both registered above.

Now, this won't work quite so nicely. Because when I have a JAX-RS **Response** like this 

`return Response.ok(Pair.of("date", LocalDateTime.now())).build();`

It will print the LocalDateTime using the default serializer (i.e. as a String) and not my custom one (as a number).

No this happens because when the **Marshaller.class** is building the Serializer for that date it won't add a Customization to the builder (here, **line 156** of Marshaller)

```
JsonbSerializer<?> getRootSerializer(Class<?> rootClazz) {
    final ContainerSerializerProvider serializerProvider = getMappingContext().getSerializerProvider(rootClazz);
    if (serializerProvider != null) {
        return serializerProvider
                .provideSerializer(new JsonbPropertyInfo()
                                           .withRuntimeType(runtimeType));
    }
    SerializerBuilder serializerBuilder = new SerializerBuilder(getJsonbContext())
            .withObjectClass(rootClazz)
            .withType(runtimeType);

    if (!DefaultSerializers.getInstance().isKnownType(rootClazz)) { // here
        ClassModel classModel = getMappingContext().getOrCreateClassModel(rootClazz);
        serializerBuilder.withCustomization(classModel.getClassCustomization());
    }
    return serializerBuilder.build();
}

```
Because it did find a **DefaultSerializer** for that Type. Since it has no Customization added to the builder, when actually building it will bypass the part of the code where it fetches a **UserSerializer**, which we see here, on line 67 of SerializerBuilder:

```
 public JsonbSerializer<?> build() {
        withRuntimeType(resolveRuntimeType());

        if (getCustomization() instanceof ComponentBoundCustomization) {
            ComponentBoundCustomization customization = (ComponentBoundCustomization) this.getCustomization();
            //First check if user deserializer is registered for such type
            final ComponentMatcher componentMatcher = getJsonbContext().getComponentMatcher();
            Optional<SerializerBinding<?>> userSerializer = componentMatcher // HERE
                    .getSerializerBinding(getRuntimeType(), customization);
            if (userSerializer.isPresent()) {
                return new UserSerializerSerializer<>(getClassModel(), userSerializer.get().getJsonbSerializer());
            }

            //Second user components is registered.
            Optional<AdapterBinding> adapterInfoOptional = componentMatcher
                    .getSerializeAdapterBinding(getRuntimeType(), customization);
            if (adapterInfoOptional.isPresent()) {
                return new AdaptedObjectSerializer<>(getClassModel(), adapterInfoOptional.get());
            }
        }

        final Optional<AbstractValueTypeSerializer<?>> supportedTypeSerializer = getSupportedTypeSerializer(objectClass);
        if (supportedTypeSerializer.isPresent()) {
            return supportedTypeSerializer.get();
        }
...
```

As we see here, if it has a Customization it will fetch the right LocalDateTimeSerializer I've programmed, otherwise it will get a supported type serializer and will just use the standard one.

So my question is: is this suposed to be like that? Shouldn't it consider the other custom serializers that might be present? Or are developers supposed to build JsonbSerializer from scratch to account for this cases? 

(Eventually I did manage to make it work by building a JsonbSerializer and passing it a Customization as I've seen in another serializer elsewhere.)

**Expected behavior**
When calling serialize on an object of a given type it should build a JsonbSerializer in such a way that it would fetch any other custom serializer implemented in the context.

**System information:**
 - OS: Windows 10
 - Java Version: 1.8.0_282 - AdoptOpenJDK
 - Yasson Version: 1.0.6

**Comment by Verdent** [comment]
Hi @CarlosMOGoncalves , thank you for reaching out and for detailed description. I have done some testing and this issue is fixed in the 1.0.7 and higher.

**Comment by CarlosMOGoncalves** [comment]
Thanks for the quick response @Verdent .

The latest version of Payara is still on 1.0.6 and has been for a while, which is why I didn't have a newer one.
Great news that is fixed!
I will try asking them to update the version in one of the next releases.

I think you can close this then.

Cheers!

**Comment by Verdent** [comment]
Resolved
