### ISSUE TITLE
PropertyNamingStrategy is not considered for JsonbCreators

### ISSUE THREAD

**Issue by bmarwell** [eclipse-ee4j/yasson#583]
**Describe the bug**

PropertyNamingStrategy is not considered for records

**To Reproduce**

* Create a record with camelCase fields
* Add a constructor (no parameters, no implementation) with `@JsonbCreator`.
* Create a propertyVisibilityStrategy:
```java
  static class PrivateVisibilityStrategy implements PropertyVisibilityStrategy {

    @Override
    public boolean isVisible(Field field) {
      return true;
    }

    @Override
    public boolean isVisible(Method method) {
      return false;
    }
  }
```
* Use the naming Strategy with underscores
* Put it all together
```java
        new JsonbConfig()
            .withAdapters(new AuthorIdAdapter())
            .withNullValues(Boolean.TRUE)
            .withFormatting(Boolean.TRUE)
            .withPropertyVisibilityStrategy(new PrivateVisibilityStrategy())
            .withPropertyNamingStrategy(PropertyNamingStrategy.LOWER_CASE_WITH_UNDERSCORES);
```

Try to read a JSON file and see this error:

```
jakarta.json.bind.JsonbException: JsonbCreator parameter firstName is missing in json document.
```

**Expected behavior**

SHould have used first_name instead.

**System information:**

 - OS: Linux
 - Java Version: 17 semeru
 - Yasson Version: 2.0.4 and 3.0.2

**Additional context**

Example on this commit: https://github.com/bmarwell/jaxrs-test-showcase/pull/61/commits/71348e8d153300a4699ec33314bb577ec1c87228

**Comment by bmarwell** [comment]
Works in Apache Johnzon. When no `@JsonbProperty` is defined on a `@JsonbCreator`, the naming strategy is being considered.

**Comment by bmarwell** [comment]
Example project with builds of:

* johnzon
* johnzon-snapshot
* yasson2
* yasson3

... is here: https://github.com/bmarwell/jsonb-creator-property-naming

Romain fixed it in johnzen literally minutes after talking to him :D

**Comment by Verdent** [comment]
Hi @bmarwell , I am finally having a little bit of time to take a look into this :-) Thank you for bringing this up and making fix for it as well.

**Comment by Verdent** [comment]
Fix merged
