### ISSUE TITLE
Is it possible to release 3.0.3 officially?

### ISSUE THREAD

**Issue by api-from-the-ion** [eclipse-ee4j/yasson#618]
I see the 3.0.3 tagged but not officially released. Can this be done?

**Comment by jamezp** [comment]
The changes also don't seem to be merged into the master branch.

**Comment by Verdent** [comment]
Hi, you mean that it is not listed among releases? I will take a look into that.

**Comment by jamezp** [comment]
The tag is there, https://github.com/eclipse-ee4j/yasson/tags, but it's not under [release](https://github.com/eclipse-ee4j/yasson/releases). The main branch seems out of date as well. It's still on 3.0.3-SNAPSHOT version and is missing the commits in the 3.0.3 tag.

**Comment by Verdent** [comment]
Yep, that is absolutely true. I will be having fix tomorrow at latest.

**Comment by bh-tt** [comment]
This can probably be closed, as 3.0.3 is available in maven central?

**Comment by mkarg** [comment]
@Verdent Why not closing this issue?

**Comment by Verdent** [comment]
@mkarg Thank you! Closing
