### ISSUE TITLE
Make yasson to honor @JsonbProperty on the getter when deserializing

### ISSUE THREAD

**Issue by onacit** [eclipse-ee4j/yasson#628]
**Is your feature request related to a problem? Please describe.**
May be or not.

**Describe the solution you'd like**
Make Yasson to honor `@JsonbProperty` on the getter when no `@JsonbProperty` defined on the setter.

**Describe alternatives you've considered**
N/A.

**Additional context**
The effectiveness of the `@JsonbProperty` for getters/setters is, at least to me, unclear.

```java
@Setter
@Getter
@EqualsAndHashCode
@ToString
public class User {

    @JsonbTransient
    private String name;

    @JsonbTransient
    private String lastName;
}
```

```java
public interface UserHolder {

    @JsonbProperty("name")
    default String getName() {
        //
    }

    // Works without @JsonbProperty, cuz it's just one word, `name`
    default void setName(String name) {
        //
    }

    @JsonbProperty("last_name")
    default String getLastName() {
        try {
            var field = getClass().getDeclaredField("user");
            if (!field.canAccess(this)) {
                field.setAccessible(true);
            }
            final User user = (User) field.get(this);
            if (user == null) {
                return null;
            }
            return user.getLastName();
        } catch (ReflectiveOperationException roe) {
            throw new RuntimeException(roe);
        }
    }

    @JsonbProperty("last_name") // Yasson tries to deserialize `lastName` without this annotation.
    default void setLastName(String lastName) {
        try {
            var field = getClass().getDeclaredField("user");
            if (!field.canAccess(this)) {
                field.setAccessible(true);
            }
            User user = (User) field.get(this);
            if (user == null) {
                user = new User();
                field.set(this, user);
            }
            user.setLastName(lastName);
        } catch (ReflectiveOperationException roe) {
            throw new RuntimeException(roe);
        }
    }
}
```
```java
@Setter // just for application
@Getter // just for application
@EqualsAndHashCode
@ToString
public class UserHolderImpl
        implements UserHolder {

    @JsonbTransient
    private User user;
}
```

I already checked that, with Jakarta JSON Binding, `@JsonbProperty` may be used on both getters and setters, especially for using different names.

>To provide custom name for given field (or JavaBean property), jakarta.json.bind.annotation.JsonbProperty may be used. JsonbProperty annotation may be specified on field, getter or setter method.

>If jakarta.json.bind.annotation.JsonbProperty is specified on getter method, it is used only for serialization. If jakarta.json.bind.annotation.JsonbProperty is specified on setter method, it is used only for deserialization.

> It is possible to specify different values for getter and setter method for jakarta.json.bind.annotation.JsonbProperty annotation. In such case the different custom name will be used for serialization and deserialization.

Can we make Yasson make the `@JsonbProperty` defined on the getter when the setter has no `@JsonbProperty`?

```java
@JsonbProeprty("whatever_named")
String getWhateverNamed() {}

//@JsonbProeprty("whatever_named") // Make yasson use `whatever_named` not `whateverNamed`
void setWhateverNamed(String whateverName) {}
```

**Comment by api-from-the-ion** [comment]
Didn't you misspell something here ? In your last example, you are using an annotation that isn't from this API and is misspelled.

There are tests for this annotation in this project, like [JsonbPropertyTest](https://github.com/eclipse-ee4j/yasson/blob/master/src/test/java/org/eclipse/yasson/customization/JsonbPropertyTest.java) and [JsonbPropertyName](https://github.com/eclipse-ee4j/yasson/blob/master/src/test/java/org/eclipse/yasson/customization/model/JsonbPropertyName.java). May you take a look at them and tell us which one you mean? By the way, all these tests are working.

**Comment by onacit** [comment]
@api-from-the-ion Yes I did, sorry. Fixed.

**Comment by api-from-the-ion** [comment]
Thank you, but in example, this is still misspelled. ;-) And did you take a look at the above mentioned tests? Are there any of them which resembles your situation? Or write your own test and publish it here.
