### ISSUE TITLE
Can't create instance of a class: interface java.util.Collection, No default constructor found.

### ISSUE THREAD

**Issue by maxencelaurent** [eclipse-ee4j/yasson#98]
Such a test fails:
```
public class DefaultCollectionInstanceTest {

    public static class Dummy {
        public Collection<String> c;
    }

    @Test
    public void testDummy() {
        JsonbBuilder.create().fromJson("{\"c\": []}", Dummy.class);
    }
}
```

org.eclipse.yasson.internal.serializer.CollectionDeserializer#createInterfaceInstance can create instances for various interfaces which extends Collection but not for Collection itself. 

Shouldn't this method be able to create instances for collections ? 
```
      if (Collection.class == ifcType) {
                return (T) new ArrayList();
      }
```

**Comment by bravehorsie** [comment]
Looks to be correct. Thanks @maxencelaurent

**Comment by Verdent** [comment]
Fixed in master.
